### ISSUE TITLE
user profile configuration

### ISSUE THREAD

**Issue by rootofdigits** [Yvand/AzureCP#100]
Hi Yvand.
Thank you for amazing framework we have fast and stable SSO now thanks to you.

our user profiles are missing attributes values. such as (display name, mobile number ...etc)

I tried to configure them via powershell and central admin > azurecp user mapping GUI nothing changed I tried all three mapping options there without and reflection on user profiles. I guessed there might be work done on azure ad which I dont have access on or it might be an issue with azurecp.

if its configuration issue could you please share the documentation guide how to configure user profile attributes?

Many thanks,
Ayman

**Comment by Yvand** [comment]
@rootofdigits thank you for your feedback!
Are you talking about profiles properties in the User Profile Application, or in the site collections?
FYI, AzureCP can only set profiles properties in the site collections, where user is added for the 1st time in the site collection

**Comment by rootofdigits** [comment]
Hi Yvand,

Thank you for your response!
Site collection users profiles missing some attributes Such as mail, job, phone etc and the display name is mail.
I am not the AzureAD admin and I don’t have access to configure trust claims and user mappings over-there but I need to know if there is a guide to help us configure the site collection to populate full profiles attributes? I believe from research that we need to add the user mapping from AzureAD portal by configuring SP Trusted Identity Token Issuer 
In SharePoint central admin AzureCP mapping for user attributes become red crossed which mean they are not provided from AzureAD if I understood correctly.

From this link I need to configure the user attributes mapping with AzureAD:
Https://SiteCollectionURL/_layouts/15/userdisp.aspx

I appreciate your support and amazing SSO solution.

**Comment by rootofdigits** [comment]
Hi Yvand,

I figured out that the AzureCP configurations are working well the research we need to do is pure AzureAD configurations in Claim user attributes.
we have conflict between choosing the identifier and display name they both have the same attribute as (required & optional claim type) when we changed display name to name users permissions lost :/
attached mapping on AzureAD
![azureadmapping](https://user-images.githubusercontent.com/24433782/93208653-8e564f00-f765-11ea-9795-05eee2f7e4ba.PNG)

**Comment by Yvand** [comment]
Ok, so AzureCP can set profiles properties in the site collections, but only for users that are added for the 1st time in the site collection.
So I suggest you you make your tests each time in a new temp site collection.

This feature does not rely on the configuration of the trust between Azure AD and SharePoint, it's a pure AzureCP configuration that you can see in central admin > security > AzureCP claims mapping page: the profile properties correspond to the column "PickerEntity metadata"

**Comment by rootofdigits** [comment]
Dear Yvand,

so after testing I find out that this is the issue as you said: "FYI, AzureCP can only set profiles properties in the site collections, where user is added for the 1st time in the site collection"
how I can add them for the first time if they already were added before we deployed AzureCP. I mean I need to perform this on existing old site collection and I am open to delete all users and add them again (if its possible please help me to reference or help me find a solution)

Many thanks,
Ayman

**Comment by rootofdigits** [comment]
my problem is:-
users with windows authentication:
display name (first and last)
work email is correct.

for azureAD authentication
display name (user email)
work email is null
