### ISSUE TITLE
Application is stuck to try login again and again 

### ISSUE THREAD

**Issue by gauravPOC** [Yvand/AzureCP#103]
When i already login on SharePoint site using Azure CP and remain same for 15 min and after 15 min when I click on any link then it is trying to validate again and stuck in a loop. PFB screenshot of the same. This is production issue therefore please help to close asap.
![ErrorSS](https://user-images.githubusercontent.com/60103218/95750997-93061880-0cbb-11eb-960e-3bbd5099a9c7.png)

**Comment by Yvand** [comment]
This symptom can have hundreds of causes, so there is nothing to say unless you provide clear technical information about what exactly is happening.
An extract of the relevant SharePoint logs or a Fiddler trace could definitely be a good start.
You can check this page to determine if this somehow caused by AzureCP: https://yvand.github.io/AzureCP/Troubleshoot-AzureCP.html

**Comment by gauravPOC** [comment]
Thanks Yuvan. Please find the attached Verbose log.
[login.zip](https://github.com/Yvand/AzureCP/files/5369810/login.zip)

**Comment by gauravPOC** [comment]
i have seen that i open site on private browsing then it work and in normal browser it stucks on login screen. i have already share the log with you. Please help. I am trying to login Gaurav-a@hcl.com

**Comment by gauravPOC** [comment]
Hi Yvan,

I have taken the fiddler log from server and uploaded. Please find the same This is a production issue and 10k user are impacted due to this. Please help to resolve this.
[wf13Fiddler.zip](https://github.com/Yvand/AzureCP/files/5376983/wf13Fiddler.zip)

**Comment by Yvand** [comment]
@gauravPOC please note that all information you share here are public.
Also, I appreciate that you have a high impact in production, but I simply cannot commit to work on such urgencies, it's a free open source project, not a commercial product.

I took a look at the Fiddler trace. You need to focus on the GET to /_layouts/15/Authenticate.aspx?Source=%2F%5Ftrust%2F 
Somehow, SharePoint rejects the user token here. Looking at the logs of this request will hopefully tell you what's wrong.
