### ISSUE TITLE
AzureCP timeout 

### ISSUE THREAD

**Issue by plantoschka** [Yvand/AzureCP#105]
We are planning to move from ADFS to authentication trough Azure AD. Therefore we are moving from LDAPCP (ADFS) to AzureCP (Azure AD).

I've prepared the necessary setup in Azure AD and set up a new TrustedTokenIssuer in SharePoint. After that I enabled it in a web application and could successfully login with my Azure AD credentials and access a SP site.

After that I setup our tenant in Azure CP Global Configuration and do all the steps from the install guide. When I click on Test the Connection I get the message "Connection successful."

After I add the tenant login trough AzureAD will not work anymore. When I remove it, login will work again.

When I try to open a site I get the following error:
After 60 seconds I get redirected to a /_trust URL with a "Server Error in '/' Application." message.
When I look in the EventViewer I see the following message:
`Security Token Service timed out [Correlation ID : 786e869f-fa87-b07c-887f-afb9082dba70 ] with exception: System.TimeoutException: The request channel timed out while waiting for a reply after 00:00:59.7968640. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout. ---> System.TimeoutException: The HTTP request to 'http://localhost:32843/SecurityTokenServiceApplication/securitytoken.svc' has exceeded the allotted timeout of 00:00:59.8740000. The time allotted to this operation may have been a portion of a longer timeout. ---> System.Net.WebException: The operation has timed out`

I've went trough the Troubleshoot section (On the SharePoint Server with the farm account)
1) Test Connectivity --- works fine
2) Obtain the access token using PowerShell --- works fine. I get a token
3) Check SharePoint logs --- It does produce any log file. Logging for AzureCP is set to Verbose

**Comment by Yvand** [comment]
@plantoschka can you set AzureCP logs to verbose and check SharePoint logs to see why it is not working?
To set AzureCP logs to verbose:

```powershell
"AzureCP:*"| Set-SPLogLevel -TraceSeverity Verbose
```

**Comment by plantoschka** [comment]
Issue is resolves. Missed this guide: https://yvand.github.io/AzureCP/Configure-AzureCP.html
After I added proxy configuration to web.exe.config it worked fine.

**Comment by Yvand** [comment]
Thank you for updating the status of the issue!
