### ISSUE TITLE
UserLogin vs. UserName

### ISSUE THREAD

**Issue by Grime121** [Yvand/AzureCP#112]
This isn't really an "issue" with the app (I don't think...), but more of a problem that we are having with implementation. The only way we have been able to get the display names to show up correctly (for instance, in the top right-hand corner of the SharePoint pages) is by setting the Unique Identifier in AzureCP to DisplayName. However, if we do that, it also changes the UserLogin values to i:0e.t\|azuread|<DisplayName>, which we do NOT want.

How do we get the user's Display Name to show up as their username, and still use their UPN for their UserLogin value?

**Comment by Yvand** [comment]
AzureCP should always set the value with the UPN, regardless of the display name which is different.
Can you check the SharePoint logs and filter on product/area "AzureCP" to see exactly how AzureCP creates the entities?

**Comment by Yvand** [comment]
And you can configure this in AzureCP "Global configuration" page, and more deeply in the "Claim types configuration" page

**Comment by Grime121** [comment]
When you say “ AzureCP should always set the value with the UPN”, which value are you referring to? The SP UserLogin value? When we change the AzureCP unique identifier to DisplayName, it is setting the UserLogin value to <claims header>|<DisplayName>, and the SP Name value to <DisplayName>. When we set the AzureCP unique identifier to UPN, it is setting the SP UserLogin value to <claims header>|<UPN>, and the SP Name value to <UPN>.

I will have to get you that info tomorrow. It’s after 3AM here, and I’ve got to get to bed. We do have a Production deployment scheduled for less than 48 hours from now though, so I will try to get it to you as soon as I can. Even if we do have to go to Production like this though, I’m not too concerned, as it only seems to be effecting the new users that we add to SP. The users that we convert using Convert-SPWebApplication do appear to be keeping their correct DisplayName value for the SP Name attribute, and only the SP UserLogin value is getting changed to the UPN format. That convert command is being run while the Trusted Token Issuer is still configured to use AzureAD though. We only change it to use AzureCP after the conversion (otherwise the Convert-SPWebApplication command fails).

**Comment by Yvand** [comment]
The user identifier is always **the trailing part**: 
i:0e.t|aadtrust|**aaduser1@tenant.onmicrosoft.com**

With Azure AD, this identifier is always the userPrincipalName (for members) and you should really not change it.
But AzureCP lets you choose a different attribute to display (here I set it to DisplayName):

![image](https://user-images.githubusercontent.com/8788631/101468343-8e6c8200-3943-11eb-8aae-2622b24454f7.png)

**Comment by Grime121** [comment]
We have ours set to OnPremiseUserPrincipleName because we do not use our On-Prem AD UPNs as the identifier when syncing our users to Azure. We use the On-Prem AD user's mail attribute to sync them to Azure. This is because we have almost 800 different domains, so it was going to be impossible to add them all as additional suffixes to our On-Prem AD. So... That is why we use OnPremisesUserPrincipleName instead of UPN for the unique identifier in AzureCP.

We do have the display setting set to DisplayName, but that is not what is being displayed in our QA Farm. What is exceptionally strange is it works as expected in our DEV Farm. Just not in our QA Farm. Both Farms use the same App Registration in Azure, and appear to have the exact same configurations in SharePoint.

QA Farm:
![image](https://user-images.githubusercontent.com/31966695/101535569-78b88600-395e-11eb-9c4f-e01f3b993b47.png)

QA Farm:
![image](https://user-images.githubusercontent.com/31966695/101536386-8e7a7b00-395f-11eb-84f3-45f5d9c0c7b0.png)

DEV Farm:
![image](https://user-images.githubusercontent.com/31966695/101537172-a7376080-3960-11eb-9621-93d420bef406.png)

DEV Farm:
![image](https://user-images.githubusercontent.com/31966695/101537100-8ec74600-3960-11eb-8b47-100f3b72dc70.png)


I can't provide you any logs for when AzureCP creates the entities because it is not even finding them when I search by DisplayName. It only finds a user when I search by their On-Prem UPN. Here are the log entries for when it fails to find a user by DisplayName, though:

12/08/2020 14:18:06.41	w3wp.exe (0x5294)	0x00BC	AzureCP	Core	1337	Verbose	[AzureCP] Getting new access token for tenant 'CED.onmicrosoft.com' on cloud instance 'AzurePublic' using client ID e154b69b-ebbb-44c7-8f11-785f3bb74351 and a client secret.	a962959f-0936-d0c2-034a-ce39647173c8
12/08/2020 14:18:06.82	w3wp.exe (0x5294)	0x45E4	AzureCP	Core	1337	High	[AzureCP] Got new access token for tenant 'CED.onmicrosoft.com' on cloud instance 'AzurePublic', valid for 1 hour(s) and retrieved in 407 ms	
12/08/2020 14:18:06.98	w3wp.exe (0x5294)	0x1FA0	AzureCP	Lookup	1337	Medium	[AzureCP] Got 0 users/groups in 552 ms from 'CED.onmicrosoft.com' with input 'Evan Talley'	d962959f-d9e0-d0c2-034a-c68683e75721

**Comment by Grime121** [comment]
We are actually having the same problem in the DEV environment now. I'm not sure what changed that could have caused the SP Name value to change from DisplayName to OnPremisesUserPrincipleName when we add new users in DEV now. It does still at least allow me to search by DisplayName, though, and the preview even shows the account as:

AzureCP
DisplayName=Sunil Kunapalli

Here's a screenshot of that:

![image](https://user-images.githubusercontent.com/31966695/101556031-82061a80-397f-11eb-9223-734938c72ab7.png)


Here are the logs from when I just added this user to a group on the SP site:

12/08/2020 17:57:57.79	w3wp.exe (0x54EC)	0x30F8	AzureCP	Lookup	1337	Medium	[AzureCP] Got 1 users/groups in 172 ms from 'CED.onmicrosoft.com' with input 'Suni'	
12/08/2020 17:57:57.79	w3wp.exe (0x54EC)	0x1EF0	AzureCP	Lookup	1337	Verbose	[AzureCP] 1 entity(ies) to create after filtering	726f959f-235e-c0f0-e7ec-29dde7d966d4
12/08/2020 17:57:57.79	w3wp.exe (0x54EC)	0x1EF0	AzureCP	Claims Picking	1337	Verbose	[AzureCP] Added entity: display text: 'Sunil Kunapalli', claim value: 'SKunapalli-c@SYSTEMS.CED.local', claim type: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn'	726f959f-235e-c0f0-e7ec-29dde7d966d4
12/08/2020 17:57:57.79	w3wp.exe (0x54EC)	0x1EF0	AzureCP	Claims Picking	1337	Medium	[AzureCP] Returned 1 entities from input 'Suni'	726f959f-235e-c0f0-e7ec-29dde7d966d4
12/08/2020 17:57:58.16	w3wp.exe (0x54EC)	0x3398	AzureCP	Lookup	1337	Medium	[AzureCP] Got 1 users/groups in 74 ms from 'CED.onmicrosoft.com' with input 'Sunil'	
12/08/2020 17:57:58.16	w3wp.exe (0x54EC)	0x1EF0	AzureCP	Lookup	1337	Verbose	[AzureCP] 1 entity(ies) to create after filtering	726f959f-b37b-c0f0-e7ec-221dc6137ea1
12/08/2020 17:57:58.16	w3wp.exe (0x54EC)	0x1EF0	AzureCP	Claims Picking	1337	Verbose	[AzureCP] Added entity: display text: 'Sunil Kunapalli', claim value: 'SKunapalli-c@SYSTEMS.CED.local', claim type: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn'	726f959f-b37b-c0f0-e7ec-221dc6137ea1
12/08/2020 17:57:58.16	w3wp.exe (0x54EC)	0x1EF0	AzureCP	Claims Picking	1337	Medium	[AzureCP] Returned 1 entities from input 'Sunil'	726f959f-b37b-c0f0-e7ec-221dc6137ea1
12/08/2020 17:58:02.99	w3wp.exe (0x54EC)	0x1EF0	AzureCP	Lookup	1337	Medium	[AzureCP] Got 1 users/groups in 175 ms from 'CED.onmicrosoft.com' with input 'skunapalli-c@systems.ced.local'	726f959f-b37b-c0f0-e7ec-221dc6137ea1
12/08/2020 17:58:02.99	w3wp.exe (0x54EC)	0x4874	AzureCP	Lookup	1337	Verbose	[AzureCP] 1 entity(ies) to create after filtering	736f959f-b368-c0f0-e7ec-20e7fb6ac450
12/08/2020 17:58:02.99	w3wp.exe (0x54EC)	0x4874	AzureCP	Claims Picking	1337	High	[AzureCP] Validated entity: display text: 'Sunil Kunapalli', claim value: 'SKunapalli-c@SYSTEMS.CED.local', claim type: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn'	736f959f-b368-c0f0-e7ec-20e7fb6ac450


This is what the user appears as, after adding them. Notice that the SP Name value is the OnPremisesUserPrincipleName, instead of the DisplayName:

![image](https://user-images.githubusercontent.com/31966695/101555691-b88f6580-397e-11eb-878f-62cbc4e9c04a.png)

**Comment by Grime121** [comment]
I discovered that if I reset the AzureCP config, and then add my tenant back, change the identifier to OnPremisesUserPrincipleName, and change the Display value to DisplayName, it fixes it. I am once again getting DisplayName for the SP Name values. I'm not sure why it stopped working in both my Farms. Hopefully it will stick this time, though, if I don't screw with any other settings in there.

**Comment by Grime121** [comment]
I just discovered that it is only working incorrectly for at least SOME users. For instance, I just added two other users, and it added them with the correct DisplayName values. When I add my own account though, it uses the OnPremisesUserPrincipleName. Why would it be working one way for one account, and another for another account? My account is coming from the same Claims source as theirs. In fact, it is our ONLY claims source (I hid the On-Prem AD source).

**Comment by Grime121** [comment]
Ah Ha! I figured it out in QA. I had to remove my old account that was still using the UPN as the displayname (using Remove-SPUser). THEN, when I added a new permission for my account, it used my correct display name.

**Comment by Yvand** [comment]
@Grime121 nice catch. To avoid this kind of confusion in such tests, you can try in new site collections, where users/groups don't exist yet in the UserInfo table.

**Comment by Grime121** [comment]
Is it safe to delete entries from the UserInfo table that have the tp_Deleted value (or whatever that column is called) set to a non-zero number? Or can that cause issues? Surely there is some way to clean up that table.... We’ve had these Content DBs going back to SP 2010, and are a fairly large company. So, there are a TON of deleted users in there. Not to mention (and more importantly) the user accounts that are no longer valid, such as the no longer used <DOMAIN>\<UserName> formatted login IDs, and now all of the Windows Claims accounts that have been replaced with Trusted Claims accounts. I’d really like to clean out all of those after 1) Converting to Claims-Based login IDs when we upgraded to SP 2013, and 2) Converting to Trusted Claims IDs during this current project.

**Comment by Yvand** [comment]
There is no supported way to delete entries from the UserInfo table, even for stale, long deleted users.

**Comment by Grime121** [comment]
That’s too bad. We’re still having some sign-in issues with one of the three sites in PROD, but it doesn’t appear to be related to AzureCP. The permissions all look correct, but users are still getting “Site is not shared with you.” Hopefully we can get it sorted out this evening, though. Thanks for helping me work that issue out with you!
