### ISSUE TITLE
Members not recognized after AzureCP installation  #110 

### ISSUE THREAD

**Issue by ooditj** [Yvand/AzureCP#114]
After installing AzureCP V16 ,when trying to add members in a SharePoint group, getting the message :"Sorry, you are not allowed to share this with external users."
 Reset the azureCP configuration and restrated timer and IIS still no luck.

we are getting following cert issue :

An operation failed because the following certificate has validation errors:

Subject Name: CN=graph.microsoft.com, O=Microsoft Corporation, L=Redmond, S=WA, C=US
 Issuer Name: CN=Microsoft Azure TLS Issuing CA 05, O=Microsoft Corporation, C=US
 Thumbprint: 48B5B869C6B5E00A14121D987DF888410C77B8D4

Errors:

The root of the certificate chain is not a trusted root authority..

An operation failed because the following certificate has validation errors:

Subject Name: CN=graph.microsoft.com, O=Microsoft Corporation, L=Redmond, S=WA, C=US
 Issuer Name: CN=Microsoft Azure TLS Issuing CA 05, O=Microsoft Corporation, C=US
 Thumbprint: 48B5B869C6B5E00A14121D987DF888410C77B8D4

Errors:

PartialChain: A certificate chain could not be built to a trusted root authority.
 RevocationStatusUnknown: The revocation function was unable to check revocation for the certificate.
 OfflineRevocation: The revocation function was unable to check revocation because the revocation server was offline.

**Comment by Yvand** [comment]
@ooditj  can you run the following script on the SharePoint server, as the application pool account, and check if it works:

```powershell
Invoke-WebRequest -Uri https://login.windows.net -UseBasicParsing
Invoke-WebRequest -Uri https://login.microsoftonline.com -UseBasicParsing
Invoke-WebRequest -Uri https://graph.microsoft.com -UseBasicParsing
```

**Comment by ooditj** [comment]
Invoke-WebRequest : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure
channel.
At line:1 char:1
+ Invoke-WebRequest -Uri https://login.windows.net -UseBasicParsing
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Invoke-WebRequest : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure
channel.

Hi Yvand, we are receiving above error for graph

Best Regards,
Oodit Jethwa

**Comment by Yvand** [comment]
@ooditj it looks like you are missing some root or intermediate certificate to access the endpoint.
You can download all the root and intermediate certificates as a P7B root cert bundle from [this page](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-office-365-certificate-chains?view=o365-worldwide) and install the missing ones in the certificate store of the machine.
Can you do that and let me know the outcome?
