### ISSUE TITLE
People Picker unreliable, timeouts

### ISSUE THREAD

**Issue by plantoschka** [Yvand/AzureCP#115]
Hello,

we've enabled AzureCP for one web application three months ago. We notice that the people picker works very unreliable. Often times I have to retype the name I'm searching for multiple times before the results appear. Sometimes this takes a couple of minutes. When I get the results it will work fine for the next couple of hours (probably the results are chached?).

When no people are found I see this message in the ULS log for AzureCP:
[AzureCP] Could not get access token before timeout of 4000 ms for tenant 'XXX.onMicrosoft.com' on cloud instance 'AzurePublic'	9654a59f-XXXX

I added proxy configuration to all necessary web sites following the install guide. 

Any ideas?

**Comment by Yvand** [comment]
@plantoschka can you try to run the following script on the SharePoint server, as the application pool account, and check if it works/how long it takes:

```powershell
Invoke-WebRequest -Uri https://login.windows.net -UseBasicParsing
Invoke-WebRequest -Uri https://login.microsoftonline.com -UseBasicParsing
Invoke-WebRequest -Uri https://graph.microsoft.com -UseBasicParsing
```

**Comment by plantoschka** [comment]
@Yvand All three commands now work fine.
I've just had to set the proxy settings in Internet Explorer for the application pool account user. People Search now also works fine.
Maybe that was the issue. I will watch this over the next couple of days and report back.

**Comment by Yvand** [comment]
Looks good, keep me posted

**Comment by plantoschka** [comment]
Works pretty reliable now. Thanks @Yvand
