### ISSUE TITLE
AzureCP configuration for guest users

### ISSUE THREAD

**Issue by plantoschka** [Yvand/AzureCP#117]
Hello,

we've configured our claim mapping in Azure based on Microsoft documentation like this:
![image](https://user-images.githubusercontent.com/2125129/107957036-536c7780-6fa0-11eb-9216-63031d40e530.png)

In AzureCP for guest user we had to change the User identitfier property to UserPrincipalName:
![image](https://user-images.githubusercontent.com/2125129/107957417-e0afcc00-6fa0-11eb-9200-12ca81c25412.png)

Sharing and access works fine but resources are shared to xyz_domain.com#ext#@ourdomain.onmicrosoft.com and not to the email address of the guest user (xyz@domain.com). This is ok but not that nice and somehow unusual for our SharePoint users.

Is it somehow possible to configure Azure and AzureCP in someway that resources are shared in a way to external guests so that only their email address or fullname is visible in the "Shared with" dialog?

**Comment by Yvand** [comment]
Hello @plantoschka, before explaining more, let me start by saying that this configuration is correct and you should keep it.

Regarding the display name, SharePoint gives a chance to claims providers (AzureCP) to set the display name **only** if the user is added for the very first time to the site collection. And no, it doesn't work to delete and re-add the user.

If the user is actually added for the 1st time (you may test in a new temp site collection), AzureCP will set the display name of the user (no matter if he is guest or not) based on this highlighted setting (in central admin > Security > AzureCP claim types configuration):

![image](https://user-images.githubusercontent.com/8788631/107968830-25dafa80-6faf-11eb-869d-8ec040029d3b.png)

In the screenshot above, it will be the Azure AD property 'DisplayName'
