### ISSUE TITLE
applying security token provider on a new web application

### ISSUE THREAD

**Issue by totayo1000** [Yvand/AzureCP#118]
Hey  Yvand

I just linked my AzureAD  to a new web applications and followed the instruction of adding a provider realm as below

$ap = Get-SPTrustedIdentityTokenIssuer -Identity "AzureAD"
$uri = new-object System.Uri("https://www.something.com")
$ap.ProviderRealms.Add($uri, "https://www.something.com/_trust/")
$ap.Update()

but when connecting  to the new web application I am getting the below:

ID4037: The key needed to verify the signature could not be resolved from the following security key identifier 'SecurityKeyIdentifier
   (
   IsReadOnly = False,
   Count = 1,
   Clause[0] = X509RawDataKeyIdentifierClause(RawData = XXXXXXXXXXX)  )

 Ensure that the SecurityTokenResolver is populated with the required key.

**Comment by Yvand** [comment]
@totayo1000 sorry but this not the right place to report this problem: Based on the symptoms it is a setup issue between your SharePoint farm and AAD, it does not relate to AzureCP.
Can you consider posting your problem on StackOverflow?

**Comment by totayo1000** [comment]
Thanks Yvand, will do as  advised
