### ISSUE TITLE
How to remove prefix in people picker after configure AzureCP

### ISSUE THREAD

**Issue by aaclage** [Yvand/AzureCP#119]
Hi Yvand, 

Hope you already have this question.
Do you know how do i remove in the people picker the claims prefix after we configure the AzureCP? 

![image](https://user-images.githubusercontent.com/8522348/110092989-841f2000-7d9a-11eb-86b9-866ae6d48f7d.png)

Thank you for you attention.

**Comment by Yvand** [comment]
Hi @aaclage, no, it cannot be removed.
Note that:
- Only the results that match the identity claim type don't have any prefix
- For the others, the text displayed, e.g. "Group", comes from the property `DisplayName` returned by `(Get-SPTrustedIdentityTokenIssuer "TRUSTNAME").ClaimTypeInformation`

**Comment by aaclage** [comment]
Hi @Yvand 

Thank you for your response and support , 

I was confuse with your first answer "_Only the results that match the identity claim type don't have any prefix_", 
Base on the claim type it's always define for "**user**", since groups cannot be incorporated in current, added new claim for groups. 
Because of that "(Groups)" prefix will appear, this statement is correct?
Bellow my configuration table:
![image](https://user-images.githubusercontent.com/8522348/110125280-6fa34d80-7dc3-11eb-8b22-fe4c732c4f3d.png)

**Comment by Yvand** [comment]
@aaclage correct, this screenshot shows 2 claim types, and only the role results will show the prefix

**Comment by aaclage** [comment]
Hi @Yvand 

It's a little annoying we are not able to use one claim for both (user & group) to retrieve both and prefix disappear but understand the technical reason.

I will close this ticket. 
Thank you very much for your support,
