### ISSUE TITLE
Using AzureCP with Multiple Web Apps

### ISSUE THREAD

**Issue by jaycallahan1973** [Yvand/AzureCP#120]
I have gotten AzureCP working with one web app with no issues but when I try to use multiple web apps I am having some issues. I am thinking this has more to do with what I am doing rather than a bug or issue with your code.  I was wanting to see if you had any direction on setting this up to work with Multiple Web apps. I either get it where it constantly loops back to the main site or it redirects me to one of the other sites. I am not sure if it is the way I am configuring the Enterprise Application in Azure or the way I am updating the SPTrustedIdentityTokenIssuer.

**Comment by Yvand** [comment]
@jaycallahan1973 AzureCP can work perfectly well with multiple web apps, IMO your problem is more a configuration issue between AAD and SP.
If you really want to rule out AzureCP you can remove it from the trust using this script:

```powershell
$t = Get-SPTrustedIdentityTokenIssuer "SPTrust"
$t.GetType().GetField("m_ClaimProviderName","NonPublic,Instance").SetValue($t, $null)
$t.Update()
```

**Comment by jaycallahan1973** [comment]
So I guess my question would be do you add 1 enterprise Application for the farm and if so do you do it like this?
![image](https://user-images.githubusercontent.com/51999317/112565481-1ec3bb00-8dab-11eb-8e1e-56734744ad58.png)

or do you add different reply URLs for each [WebApp.](url)
I have tried several different ways, but never with the results I desire. 

And same for the SPTrustedIdentiyTokenIssuer.  I added several realms and the affect was the website redirecting to one of the others.  I may be making this harder than it is.

**Comment by jaycallahan1973** [comment]
I was correct in the fact i was making this more complicated than it was.  Just added the URLs to the  Reply URL (Assertion Consumer Service URL), and then ran
$t = Get-SPTrustedIdentityTokenIssuer "AzureAD"
 $t.UseWReplyParameter=$true
 $t.Update()

I made the mistake of putting the /_Trust/ on the end of the extra web applications.  Closing this out but thanks for the response.
