### ISSUE TITLE
Dealing with Duplicate Entries due to multiple Claims Provider

### ISSUE THREAD

**Issue by Charlie-Gunn** [Yvand/AzureCP#122]
Hi Yvand,

This is a question more than a bug I think. We have some user entries in AzureAD which will share a number of details with the same users AD claim such as their email for example. When searching in a people picker field we require exact matches on AzureCP which we use to filter out the AD duplicates which works for searching.

However if you assign a user via People Picker to a field on a list item using their AD username. Save the list item, and then edit it again it then picks up the duplicate entries and asks the user to resolve. It will do this every time the user edits the list item which is non-ideal as not all users will correctly identify which one is the correct claim.

With the aim of solving this is there a way we can filter out duplicate entries from AzureAD without hindering the ability to share with guest users? I get the feeling I might be missing something really simple as we dont have this issue with previous claims providers on older instances.

**Comment by Yvand** [comment]
hi @Charlie-Gunn, during validation (when a user is already added and is displayed again), SharePoint should never receive multiple results.
Where do those multiple results exactly come from (which claims providers return them)?
How many authentication modes are enabled on the web application ?

**Comment by Charlie-Gunn** [comment]
Hi @Yvand we have two AD Forests (one of which hosts the domain on which SharePoint is present) as well as users coming in from AzureAD. People picker is able to return results from all three of these claims. 

Domain 1 and Domain 2 both authenticate via their AD claim to SP. These domains dont share any users. But both have accounts present in our AzureAD Platform. This isnt something I can get changed for reference and as far as I am aware its AD synced so user properties will be close to identical. 

The problem manifests as below:

I am adding a user from the Local AD domain to a person field on the list item. I am selecting the local AD claim via their username and saving the list item. When I edit this same list item later I am forced to pick from either the users Local AD claim, or their AzureAD claim. I want to know if there is a way to get around this or if this is intended. One guess was knowing if there is a way to filter which groups AzureCP is able to people users from?

**Comment by Yvand** [comment]
@Charlie-Gunn so do I understand correctly that 1 user comes from AD and 1 user comes from AAD (AzureCP)?

**Comment by Charlie-Gunn** [comment]
@Yvand So both accounts are relate to the same user (hence why they are identical in this case).

But you are correct that 1 comes from **AD** and 1 comes from **AAD (AzureCP)**

**Comment by Yvand** [comment]
Sorry for my late reply.
AzureCP does not offer a way to filter AAD objects based on their group membership.
Did you consider filtering results on AD side, using property [SPPeoplePickerSettings.ActiveDirectoryCustomFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.administration.sppeoplepickersettings.activedirectorycustomfilter?view=sharepoint-server#Microsoft_SharePoint_Administration_SPPeoplePickerSettings_ActiveDirectoryCustomFilter) ?

**Comment by Charlie-Gunn** [comment]
Not a viable option with the setup and requirements unfortunately as I did pose this as an option.

Thank you for the information.
