### ISSUE TITLE
4000ms timeout after every request

### ISSUE THREAD

**Issue by peretimo** [Yvand/AzureCP#124]
We have implemented AzureCP for the second time already, after not being successful the first time. Still we’re facing the same issues we had before, which is that AzureCP runs into a 4000ms timeout after every request we send, which in turn gives no results back in the people picker mask. The problem is that my team does not administrate Azure AD and has no direct access to the Azure Portal, so we cannot check any issues there (we were suspecting an issue with the dynamic groups that Accenture uses). But we have implemented all installation, configuration and troubleshooting steps from your guide on azurecp.yvand.net and in the process we mitigated many issues. Still we can’t get it running.

It would really mean a lot to me if you could spare a minute to maybe at least point us in a direction for troubleshooting. If any evidence or logs etc. are needed, I can provide those.

Merci beaucoup!

**Comment by Yvand** [comment]
@peretimo in such case, the section to ["Inspect the actual traffic between AzureCP and Azure AD"](https://azurecp.yvand.net/docs/help/troubleshooting/#inspect-the-actual-traffic-between-azurecp-and-azure-ad) should really help you see what is going wrong. Have you tested it?
What do logs say?
