### ISSUE TITLE
 $trust.ClaimProviderName = "AzureCP" Exception setting "ClaimProviderName": "Claim provider with name AzureCP does not exist." At line:1 char:1

### ISSUE THREAD

**Issue by upatel911** [Yvand/AzureCP#125]
Not working. I have deactivate and reactivate the feature under Central Admin.
I have removed the solution and reinstalled it again but still the same error.

![image](https://user-images.githubusercontent.com/64625880/121722190-1ed27d80-cab3-11eb-99bb-9210027e6c5c.png)

**Comment by Yvand** [comment]
@upatel911, sorry for the late reply. Does cmdlet [Get-SPClaimProvider](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spclaimprovider?view=sharepoint-ps) return AzureCP?

**Comment by upatel911** [comment]
Hello ,

The issue resolved when I deactivate and activate the farm feature.

Thank you so much for connecting and providing your prompt response.

Many Thanks
Uday Patel
