### ISSUE TITLE
Differentiating People Picker results from different providers

### ISSUE THREAD

**Issue by Getoffmypatch** [Yvand/AzureCP#126]
Hi @Yvand 

We are using an extended web application with the original web/app using On-Prem AD and AzureCP configured to return users from Azure AD for the extension. The problem we have is that when you are looking to add users it returns the same user from both AD. We are trying to figure out a way that distinguish AD user from AAD user so that end users dont get confused about which one to choose. We have played with the idea of setting the "Display of user identifier results" as Mail but this impacts the displayed user name when the user is added. 

Do you have some suggestion how to differentiate the same users returned from different IDP

Thanks,
Shane

**Comment by Getoffmypatch** [comment]
![image](https://user-images.githubusercontent.com/32172026/122037561-9878ad00-cdcc-11eb-97de-f4e3e3bd8978.png)

**Comment by Yvand** [comment]
@Getoffmypatch you can set a prefix for all AAD results. It can be done only through PowerShell, by setting property `EntityDisplayTextPrefix`:

```powershell
Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")
$config.EntityDisplayTextPrefix = "(SomePrefix) "
$config.Update()
```

**Comment by Getoffmypatch** [comment]
Thanks but that would impact the display name also. Is there a way that it only differentiates the lookup?

**Comment by Yvand** [comment]
@Getoffmypatch it is true but it cannot be avoided, because SharePoint uses the same property for both.
But eventually, the display name will be updated by the job which syncs data from the User Profile Service
