### ISSUE TITLE
Azure CP is not working at site collection level 

### ISSUE THREAD

**Issue by akkindus** [Yvand/AzureCP#127]
Azure CP is not working at site collection level for existing SharePoint web application, but same solution is working for newly created we application even with site collection. 

Note : Existing site collection has public DNS pointed and SSL configured at load balancer level. 
           Azure authentication provider is configured as a SPTrustedIdentityTokenIssuer for both application. 

Thanks in advance.

**Comment by Yvand** [comment]
Can you check SharePoint logs and filter on Product/Area "AzureCP" to see what happens when you search in the people picker?

**Comment by akkindus** [comment]
Here is the error we found in ULS logs -

Unexpected [AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes) 3748d49f-2278-7098-2d59-e9c4cf06a353

Also, we observed, it does not work if the site has an alternate access mapping(Custom DNS ) pointed to the webapplication.

It does work if we switch back to a machine hostname(default local url).

Thanks,
Akhilesh


________________________________

**Comment by akkindus** [comment]
When I search into the people picker it does not pull the Azure cloud users, Only I can get Local AD users.

**Comment by Yvand** [comment]
On the SharePoint server which throws this error, can you check the version of this file:
`"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll"`

**Comment by akkindus** [comment]
This is something i can see-

[cid:984c630d-1165-4dd3-ada8-9cb2bd4a5437]
________________________________

**Comment by akkindus** [comment]
[](url)

**Comment by akkindus** [comment]
The issue has been closed by mistake, Could you please re-open it? So that I can post the comment on it.

________________________________

**Comment by Yvand** [comment]
@akkindus I reopened it for you but you could do it yourself. Also, screenshot is not very convenient, please copy as text

**Comment by akkindus** [comment]
Hi Here is the clr.dll version.!

File Version          4.7.3750.0
Product Version   4.7.3750.0

**Comment by akkindus** [comment]
Hi @Yvand , Any update for me.

**Comment by Yvand** [comment]
@akkindus can you run this PowerShell cmdlet and let me know if it succeeds:

```powershell
[System.Reflection.Assembly]::Load("System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
```

**Comment by akkindus** [comment]
CONFIDENTIAL

Hi,

Here is the output of the command -

PS C:\Windows\system32> [System.Reflection.Assembly]::Load("System.Net.Http, Vesion=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")

GAC    Version        Location
---    -------        --------
True   v4.0.30319     C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll




________________________________

**Comment by akkindus** [comment]
Sorry to chess you but I have urgent need of solution.

Please update - If any...!

**Comment by Yvand** [comment]
To be honest, I cannot explain why AzureCP cannot load System.Net.Http 4.2.0.0, while it works perfectly fine in plain PowerShell.
But AzureCP uses [Microsoft.IdentityModel.Clients.ActiveDirectory](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/5.2.6), which needs [System.Net.Http (>= 4.3.4)](https://www.nuget.org/packages/System.Net.Http) (not version 4.2.0.0).
So I propose you test to manually install [System.Net.Http 4.3.4](https://www.nuget.org/packages/System.Net.Http) in the GAC of the SharePoint servers:

- Manually download [System.Net.Http 4.3.4](https://www.nuget.org/packages/System.Net.Http)
- Install it in the GAC using this script

```powershell
[System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a") | Out-Null
$publish = New-Object System.EnterpriseServices.Internal.Publish
$publish.GacInstall("C:\path-to-System.Net.Http 4.3.4\System.Net.Http.dll")
Write-Host "Assembly was successfully added to the GAC."
```

- iisreset

Please let me know the result

**Comment by akkindus** [comment]
I have a production environment, will this affect anything?

**Comment by Yvand** [comment]
This is a fairly safe action, as you are only adding a .NET assembly to the cache. And you can easily remove it if needed

**Comment by akkindus** [comment]
CONFIDENTIAL

Do we need to install this package on all SharePoint servers? would it be possible to share the process of revert back the changes in case something goes wrong - as we have a running production environment?


________________________________

**Comment by Yvand** [comment]
You can install it on only 1 SharePoint server (and test AzureCP on that server only, after you ran iisreset).
If you need to uninstall the assembly, you can simply remove its folder using the file explorer. It will be located at "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Net.Http\v4.0_4.1.1.3__b03f5f7f11d50a3a"

**Comment by akkindus** [comment]
CONFIDENTIAL

I followed the mentioned steps to install System.Net.Http 4.3.4<https://www.nuget.org/packages/System.Net.Http> dll and reset the IIS but still the same issue.

AzureCP is only working for assigning Web application user policy at central admin.

l also checked the logs but did not find any related error

________________________________

**Comment by akkindus** [comment]
Is there any paid support available?

**Comment by Yvand** [comment]
@akkindus this is not a commercial product, it is a free, open source project and there is no paid support available.
About your error, you said that you checked the logs and did not find any related error. What do you mean exactly? Is the original System.IO.FileNotFoundException gone?

**Comment by akkindus** [comment]
CONFIDENTIAL

Error is still there recently I performed a search which is logged below error in the log file -

Unexpected [AzureCP] Unexpected error occurred while setting client context for tenant 'mydomain.onmicrosoft.com'.: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.,

Callstack:    at azurecp.AADAppOnlyAuthenticationProvider..ctor(AzureCloudInstance cloudInstance, String tenant, String clientId, String clientSecret, String claimsProviderName, Int32 timeout)     at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout) 2fe1da9f-f211-7098-2d59-e1101b969ec0

07/12/2021 19:06:26.09 w3wp.exe (0x19394)                       0x18C24 AzureCP                       Lookup                         1337 Unexpected [AzureCP] Cannot query Azure AD tenant 'mydomain.onmicrosoft.com' because it was not initialized
07/12/2021 19:06:26.09 w3wp.exe (0x19394)                       0x18C24 AzureCP                       Lookup                         1337 Medium   [AzureCP] Got 0 users/groups in 0 ms from 'mydomain.onmicrosoft.com' with input 'aksingh'
________________________________

**Comment by Yvand** [comment]
@akkindus I believe I found a fix for this netstandard issue. I did some research:
Based on https://github.com/dotnet/standard/issues/542, .NET 4.7 projects should explicitely add a reference to netstandard if a reference needs its (which is true with AzureCP).
Based on https://github.com/dotnet/msbuild/pull/2567, that explicit reference should no longer be necessary and setting `DependsOnNETStandard` should be enough, but it had no effect during my tests.
So I decided to add both (explicit reference to netstandard + setting `DependsOnNETStandard`) in commit https://github.com/Yvand/AzureCP/commit/2f5cf30d0abd57f565a81c4b2d91f01eff2e4bda.
To be complete, I also added an explicit reference to System.Net.Http, but sadly it has no effect (System.Net.Http.dll is not added to the list of dependencies).

Regarding your netstandard issue: I suggest that you download asset "AzureCP-20.0.20210713.1293-dependencies.zip" from the [beta release I just created](https://github.com/Yvand/AzureCP/releases/tag/20.0.20210713.1293) and extract netstandard.dll (do not extract anything else).
Then you can install this netstandard.dll to the GAC of a SharePoint server using this script:

```powershell
[System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a") | Out-Null
$publish = New-Object System.EnterpriseServices.Internal.Publish
$publish.GacInstall("C:\Users\yvand\Downloads\AzureCP-20.0.20210713.1293-dependencies\netstandard.dll")
Write-Host "Assembly was successfully added to the GAC."
```

Then, iisreset and check if the issue is resolved

**Comment by akkindus** [comment]
CONFIDENTIAL

We are going to test it again by tommarow

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by akkindus** [comment]
CONFIDENTIAL

Hi Yvand,

We have installed the AzureCP from the scratch after removing it completely from the sharepoint farm.


We followed the mentioned steps and added dependecies to avoide netstandard dll issue.


But still we are seeing the same behavior where AzureCp only working at central admin level to populate the azure accounts in the people picker.

Any suggestions?


Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Yvand** [comment]
@akkindus assuming you still get the same error `System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral`, I'm out of ideas.
AzureCP targets .NET framework 4.7.2, not .NET standard. I assume that one of the dependencies need it, but I don't know why this would even be a problem because [.NET Framework 4.7.2 supports .NET Standard 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).
It looks like the local installation of .NET Framework is missing assemblies, but I don't know how to exactly determine which are those ones.

**Comment by akkindus** [comment]
CONFIDENTIAL

Just letting you know we are using a single URL like-  https://mysite.domain.com for internal and public access and there are load balancer configured to balance the traffic on this URL.
________________________________

**Comment by Yvand** [comment]
@akkindus so it seems that you did fix the original error `System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral` ?
To find out what's wrong now, as usual you can check the SharePoint logs and filter on Product/Area "AzureCP"
