### ISSUE TITLE
The user does not exist or is not unique when adding a 'member user'

### ISSUE THREAD

**Issue by rajh25** [Yvand/AzureCP#128]
Hello, 

I am trying to add a member user and getting error 'The user does not exist or is not unique' . I have extended the web application and enabled Azure AD claims on default zone and Windows on Intranet. Tried vice versa but still unable to add users. 

Thanks in advance

**Comment by Yvand** [comment]
@rajh25 can you look at the SharePoint logs and filter on product/area "AzureCP" to see what is going wrong?
