### ISSUE TITLE
AzureCP and LdapCP in the same farm

### ISSUE THREAD

**Issue by jedv** [Yvand/AzureCP#13]
Hello Yvand,

I have one web application using ADFS authentication, I have a Trusted Identity Provider for that. Everything works fine with LdapCP.
I have a second web application in the same SharePoint farm where I want to authenticate Azure AD users.
Is it possible to create a second Trusted Identity Provider and use AzureCP to retrieve Azure AD users in the people picker ? Or can I configure LdapCP and AzureCP in the same Trusted Identity Provider ?

Thanks in advance.

**Comment by Yvand** [comment]
Hi @jedv, yes it is safe to use AzureCP and LDAPCP in the same farm (I have this setup for a very long time), but each must be associated to its own SPTrustedLoginProvider (SPTrustedIdentityTokenIssuer)

**Comment by jedv** [comment]
Hi,

Thanks for your answer. 

When I add a second SPTrustedIdentityTokenIssuer with AzureCP as ClaimProviderName, seems like there is a side-effect : 
the first web application configured with the first SPTrustedIdentityTokenIssuer seems to use the second one (i'm redirected with the DefaultProviderRealm of the second SPTrustedIdentityTokenIssuer)
Did you encounter this issue ?

Thanks in advance.

**Comment by Yvand** [comment]
I'm not sure to understand: each SPTrustedIdentityTokenIssuer has its own DefaultProviderRealm / ClaimProviderName.
I don't see how LDAPCP's SPTrustedIdentityTokenIssuer could use the DefaultProviderRealm set in AzureCP's SPTrustedIdentityTokenIssuer

**Comment by jedv** [comment]
Each SPTrustedIdentityTokenIssuer has its own DefaultProviderRealm/ClaimProvider
The ADFS one : LDAPCP
The AzureAD one : AzureCP
When I browse a siteURL from the web application using the ADFS SPTrustedIdentityTokenIssuer i'm redirected here : 
https://[adfsURL]/adfs/ls?wa=wsignin1.0&wtrealm=urn%3asharepoint%3a[URN of ADFS SPTrustedIdentityTokenIssuer]&wctx=[siteURL]%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252F&wreply=[siteURL]%2f_trust%2fdefault.aspx

when I browse a siteURL from the web application using the AzureAD SPTrustedIdentityTokenIssuer i'm redirected here :
https://[adfsURL]/adfs/ls?wa=wsignin1.0&wtrealm=urn%3asharepoint%3a[URN of ADFS SPTrustedIdentityTokenIssuer]&wctx=[siteURL]%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252F&wreply=[siteURL]%2f_trust%2fdefault.aspx

It seems like the web application takes the ADFS SPTrustedIdentityTokenIssuer whatever I configure

**Comment by Yvand** [comment]
This is weird. To clarify your setup, can you run this script:
```powershell
Add-PSSnapin "Microsoft.SharePoint.PowerShell"
$wa = Get-SPWebApplication "http://spsites/"
$wa.AlternateUrls
foreach ($zone in [System.Enum]::GetNames( [Microsoft.SharePoint.Administration.SPUrlZone] )){
    Write-Host "Get settings for zone $zone :"
    $wa.IisSettings[$zone].ClaimsAuthenticationProviders
}
```

**Comment by jedv** [comment]
For each web application, I have Default and Intranet zone.

This is the configuration for the web application using the ADFS SPTrustedIdentityTokenIssuer :
Get settings for zone Default :
DisplayName                        : Windows Authentication
ClaimProviderName                  : AD
AllowAnonymous                     : False
UseBasicAuthentication             : False
DisableKerberos                    : True
UseWindowsIntegratedAuthentication : True
AuthenticationRedirectionUrl       : /_windows/default.aspx
UpgradedPersistedProperties        :

Get settings for zone Intranet :
DisplayName                  : ADFS
LoginProviderName            : ADFS
ClaimProviderName            : LDAPCP
AuthenticationRedirectionUrl : /_trust/default.aspx?trust=ADFS


This is the configuration for the web application using the AzureAD SPTrustedIdentityTokenIssuer :
Get settings for zone Default :
DisplayName                        : Windows Authentication
ClaimProviderName                  : AD
AllowAnonymous                     : False
UseBasicAuthentication             : False
DisableKerberos                    : True
UseWindowsIntegratedAuthentication : True
AuthenticationRedirectionUrl       : /_windows/default.aspx
UpgradedPersistedProperties        :

Get settings for zone Intranet :
DisplayName                  : AzureAD
LoginProviderName            : AzureAD
ClaimProviderName            : AzureCP
AuthenticationRedirectionUrl : /_trust/default.aspx?trust=AzureAD
UpgradedPersistedProperties  :

**Comment by Yvand** [comment]
The configuration is correct, so I'm thinking about all possible explanations.
Are you 100% the IIS websites / AAMs are not mixed up between both web apps?
Could you be hitting ADFS web app instead of AzureAD web app without noticing it?

**Comment by jedv** [comment]
AAMs don't seem to be mixed up between both web apps.
Before naming the Azure AD SPStrustedIdentityTokenIssuer "AzureAD", I named it "AAD" : it came first in the SPTrustedIdentityTokenIssuer list. The web application using ADFS SPTrustedIdentityTokenIssuer had the side-effect.
