### ISSUE TITLE
what is custom signin page to provide in authentication provider in web application in central admin?

### ISSUE THREAD

**Issue by VipinKKhandelwal** [Yvand/AzureCP#132]
Hi Yvanne, I have configured AAD authentication in my SharePoint 2019 farm using AzureCP where we have already setup LDAPCP configured. for my web application, AAD authentication provider is selected only. Problem is, when I browser a site, it goes to default login page where it lists out windows authentication and AzureADTrust where i manually select AzureADTrust auth provider. I want by default the site redirect to AAD authentication page. How to provide custom signin page for this?

**Comment by Yvand** [comment]
Hi @VipinKKhandelwal, I suggest you look at project https://github.com/Yvand/SPBypassLoginPage, which allows you to set the authentication mode to use per web application

**Comment by VipinKKhandelwal** [comment]
Hi Yvanne, Thanks for your response. This spbypasspage helped in bypassing authentication method option page. We have successfully setup Azure AD authentication but it would be great if you could help in below 2 issues - 

1. I moved one content database from webapp1(having adfs authentication) to webapp2(having azure ad authentication with azurecp) but permission is not working in site when it moved to webapp2. How to fix this or migrate user permissions. Both ADFS and AAD auth providers are having different permission type for same user.
2. While using AzureCP, UPN is showing but display name should show up in site permissions.

**Comment by Yvand** [comment]
@VipinKKhandelwal 
1. Migrating user and group permissions is a wide topic which goes much beyond the scope of such a discussion. I suggest you start by looking at articles https://joshroark.com/keeping-sharepoint-happy-during-your-domain-migration/ and https://www.linkedin.com/pulse/best-practice-when-migrating-users-sharepoint-yvan-duhamel/
2. The display name is ultimately set by the timer job which synchronizes the user properties from the User Profile Service
