### ISSUE TITLE
Tenant switches to AzurePublic on its own

### ISSUE THREAD

**Issue by vargasfe** [Yvand/AzureCP#133]
I had this issue with version 18 and so I decided to try the new release of 19.0.20210211.1285 but it  has the same issue.
I define a tenant that is in the AzureUSGovernment Cloud and at first people picker works as expected.

After some hours, it stops working and when I look at the configuration, it is now set to AzurePublic.

I have to keep removing and adding the tenant but it continues to fail.

I have tried resetting the configuration and starting from scratch but eventually it changes back to AzurePublic.

I see these entries in the SP logs periodically and I believe this is when the configuration is changed.

Updated property ClaimsProviderVersion from "15.2.20191031.1012" to "19.0.20210211.1285" in configuration "AzureCPConfig".
Configuration 'AzureCPConfig' was updated successfully to version 3578801 in configuration database.
Configuration 'AzureCPConfig' was upgraded in configuration database and some settings were updated or reset to their default configuration

**Comment by Yvand** [comment]
Based on the log above, I believe that the servers which recorded this message is running with AzureCP v15, which can definitely cause this behavior.
You need to update the AzureCP bits on that server as documented in https://azurecp.yvand.net/docs/usage/install/#finish-the-installation
