### ISSUE TITLE
Install step "Enable the claims provider" not working

### ISSUE THREAD

**Issue by JenTonUg** [Yvand/AzureCP#136]
I'm trying to install AzureCP on a fresh Sharepoint 2019 Farm (16.0.10379.20000), and followed the instructions as mentioned on the website. When I get to the step where I should activate the claims provider I get the following error:
`$trust = Get-SPTrustedIdentityTokenIssuer "SPTRUST NAME"`
`Get-SPTrustedIdentityTokenIssuer : A valid object could not be read from the provided pipebind parameter.`
When I run Get-SPTrustedIdentityTokenIssuer on it's own, I get no output. I installed with the safe method, I restarted IIS and the timer service after installing the dependencies on the non-ca servers, and I checked that the solution is globally deployed, which it is. I must be overlooking something, but I can't seem to find it. Can you steer me in the right direction? 
Thank you!

**Comment by Yvand** [comment]
@JenTonUg can you open a new PowerShell process, run `Get-SPTrustedIdentityTokenIssuer` with no parameter and see if it works.?

**Comment by JenTonUg** [comment]
@Yvand I can run it without error, but it produces no results.

**Comment by Yvand** [comment]
A prereq before you can configure AzureC is to create a SPTrustedIdentityTokenIssuer, as documented in https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial
Did you complete the steps in this article ?

**Comment by JenTonUg** [comment]
Ah, I had no idea. I'll check it out, thank you!

**Comment by JenTonUg** [comment]
Looks like that was it, thank you very much for pointing me where to go!
