### ISSUE TITLE
ResolvePrincipal did NOT find a match

### ISSUE THREAD

**Issue by daniarno** [Yvand/AzureCP#137]
Hi, we are using SharePoint 2013 Foundation together with Azure AD and AzureCP.
Generally, everything works as it should. However, we have a bigger problem with one particular user. As soon as I add the user to a SharePoint group (e.g. Owner group), the error message "User cannot be found" is displayed. The following error messages are logged in the ULS log.

GetUserInfoFromMembershipProvider: Called method. SiteID: '6ee1d6c4-afb5-44d4-b66e-f3806fcafa42', LoginName: 'i:0e.t|azuread|**@**.ch', bIsRole: 'False'.

[AzureCP] Validation failed: found 0 entities instead of 1 for incoming claim with value '**.**@**.ch' and type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn'

[Forced due to logging gap, cached @ 11/23/2021 11:25:45.74, Original Level: Verbose] SQL connection time: 0.0537 for Data Source=SHAREPOINT;Initial Catalog=SPF2013_Config;Integrated Security=True;Persist Security Info=False;Enlist=False;Pooling=True;Min Pool Size=0;Max Pool Size=100;PoolBlockingPeriod=Auto;Asynchronous Processing=False;Connection Reset=True;MultipleActiveResultSets=False;Replication=False;Connect Timeout=15;Encrypt=False;TrustServerCertificate=False;Load Balance Timeout=0;Packet Size=8000;Type System Version=Latest;Application Name=".Net SqlClient Data Provider";User Instance=False;Context Connection=False;Transaction Binding="Implicit Unbind";ApplicationIntent=ReadWrite;MultiSubnetFailover=False;TransparentNetworkIPResolution=True;ConnectRetryCount=1;ConnectRetryInterval=10;Column Encryption Setting=Disabled

GetUserInfoFromMembershipProvider: ResolvePrincipal did NOT find a match. WebApp: '352c7911-7c2c-409b-bcd7-24427072b5c3', LoginName: 'i:0e.t|azuread|**.**@**.ch', bIsRole: 'False'.

GetUserInfoFromMembershipProvider: Request is in a web context and we can't find the user so we are failing. WebApp: '352c7911-7c2c-409b-bcd7-24427072b5c3', LoginName: 'i:0e.t|azuread|**.**@**.ch', bIsRole: 'False'.

GetUserInfoFromMembershipProvider: Returning result. WebApp: '352c7911-7c2c-409b-bcd7-24427072b5c3', LoginName: 'i:0e.t|azuread|**.**@**.ch', bIsRole: 'False', UserFound: 'False', UserKey: ''.

Do you have any idea whats is going wrong?

**Comment by Yvand** [comment]
@daniarno so it looks like, somehow, AzureCP cannot find this user in AAD.
To understand why, it could be helpful to inspect the traffic from AzureCP to AAD to troubleshoot the query. You can find how to do this in [this page](https://azurecp.yvand.net/docs/help/troubleshooting/#inspect-the-traffic-to-azure-ad).
Can you give this a try?

**Comment by daniarno** [comment]
@Yvand we have not found a solution yet. Would it be possible that you could support us in a remote session? Of course we would compensate you for your efforts.

**Comment by Yvand** [comment]
@daniarno have you tried the steps in my previous message?
Doing this will allow you to see exactly what query is sent to AAD, and what results AAD returns, and understand why AAD returns nothing (I assume this is what happens).
I am happy to help but this is a free, open source project, which I develop to contribute to the ecosystem, I don't make money with it.

**Comment by daniarno** [comment]
@Yvand We have been able to solve this problem. The problem was that for the users created before 31.08.2014 the property "userType" was not set.
Thank you for your support.
