### ISSUE TITLE
Sharepoint 2019 peoplepicker doesnt return azure AD users

### ISSUE THREAD

**Issue by saep202009** [Yvand/AzureCP#139]
Hi we have some problem in our SharePoint (SP) 2019 project. When we trying to search people (azure AD users) in peoplepicker we return nothing in UI but we return following error in ULS log:

01/06/2022 15:12:36.09 	w3wp.exe (0x3D90)                       	0x32F8	AzureCP                       	Claims Picking                	1337	Unexpected	[AzureCP] Unexpected error occurred in FillSearch: System.ArgumentNullException: Value cannot be null.  Parameter name: source, Callstack:    at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)     at System.Collections.Generic.List`1.FindAll(Predicate`1 match)     at azurecp.OperationContext.InitializeSearch(List`1 processedClaimTypeConfigList, Boolean exactSearch)     at azurecp.AzureCP.FillSearch(Uri context, String[] entityTypes, String searchPattern, String hierarchyNodeID, Int32 maxCount, SPProviderHierarchyTree searchTree)	8d1e14a0-0847-b0e6-edce-cd6e1d2e7ade

We have instaled on SP lastest AzureCP solution (version 19.0.20210211.1285 )Could you somebody help us please? Thanks a lot.
Michal

**Comment by Yvand** [comment]
hi @saep202009, this is very unexpected.
Where do you get this error.
Do you repro it whatever you type in the people picker?
Can you check if you can reproduce the issue using this script:

```powershell
Add-Type -AssemblyName "Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c"
Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
# Set those 2 parameters based on your environment
$context = New-Object Uri ("http://spsites/")
$inputValue = "user"

[Microsoft.SharePoint.WebControls.PickerEntity []] $entities = $null
$claimsProvider = New-Object -TypeName azurecp.AzureCP ("AzureCP")
$entityTypes = @("User", "FormsRole")

Write-Host "Testing search with input '$inputValue'"
$entitiesList = New-Object -TypeName 'System.Collections.Generic.List[Microsoft.SharePoint.WebControls.PickerEntity]'
$result = $claimsProvider.Search($context, $entityTypes, $inputValue, $null, 30);
$entitiesList.AddRange($result.EntityData)
foreach ($children in $result.Children) {
    $entitiesList.AddRange($children.EntityData)
}
$entities = $entitiesList.ToArray()
Write-Host "Found $($entities.Count) entities:"
foreach ($entity in $entities) {
    Write-Host "Entity key: '$($entity.Key)', value '$($entity.DisplayText)'"
}
```

**Comment by saep202009** [comment]
Hi Yvand i tried to run your script and result in 0
![image](https://user-images.githubusercontent.com/70706181/149129123-fac9cd49-fc80-44c9-a55a-83ecc10388e6.png)

**Comment by Yvand** [comment]
@saep202009 can you check if it reproduced the error in the SharePoint logs .

**Comment by saep202009** [comment]
Yvand i try to get more details for you, this bug is in our SP UI when we trying to delegate task for approving document. this is not exactly SP picker see picture, we try to investigate in our custom code next.
![image](https://user-images.githubusercontent.com/70706181/149155151-b7e94502-9c30-4d35-aa84-ca9f8ac66d2e.png)

**Comment by saep202009** [comment]
> @saep202009 can you check if it reproduced the error in the SharePoint logs ?

no any errors in log after running your script

**Comment by saep202009** [comment]
not from central admin site, its in portal site with url like https://ourservername.com/SitePages/Moje%20ke%20schválení.aspx (see picture above)

**Comment by ondrejtucny** [comment]
Let me clarify: The error happens when using the Office UI Fabric people picker component in a custom app part. Repro using your script from PowerShell. The original exception posted was located in ULS logs. That's why it seems as an AzureCP bug to us.

**Comment by Yvand** [comment]
@ondrejtucny yes it seems to be a bug in AzureCP, especially if you repro with the PowerShell script.
Do you repro it all the time, regardless of the input?
I think the FillSearch method is rarely used in latest versions of SharePoint, I'll test the method on my side soon (hoipefully tomorrow) and I'll let you know if I can repro.

**Comment by Yvand** [comment]
@saep202009 the exception occurs probably because there is something wrong/unexpected in your claim types list.
Can you go to central admin > Security > AzureCP Claim types configuration and send me a screenshot of this page?

**Comment by saep202009** [comment]
@Yvand here screenshot of zour requested page
![image](https://user-images.githubusercontent.com/70706181/151139520-ca70e1ce-337a-4068-a1d5-5fe99786d85c.png)

**Comment by Yvand** [comment]
The claim types configuration is the default one and is totally fine.
I must be missing something but I'm not sure what. Do you have custom alternate access mappings with different private/external urls
