### ISSUE TITLE
Azure AD authentication failing after changing claims provider to AzureCP

### ISSUE THREAD

**Issue by mleary9** [Yvand/AzureCP#14]
I followed all instructions and installed AzureCP and created App in Azure AD.  After changing the claims provider name as follows:
$trust = Get-SPTrustedIdentityTokenIssuer "AzureAD New"
$trust.ClaimProviderName = "AzureCP"
$trust.Update()

When i try to authenticate to SharePoint i get the following error in event log
EventID 8306
An exception occurred when trying to issue security token: The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs..
EventId 8307
An exception occurred in AzureCP claim provider when calling SPClaimProvider.FillUserKeyForEntity(): Object reference not set to an instance of an object..
and attached .NET error
[azurecperror.txt](https://github.com/Yvand/AzureCP/files/1798741/azurecperror.txt)

**Comment by Yvand** [comment]
Hello, can you send a screenshot of the claims mapping page? 
It is in central administration > Security > AzureCP claims mapping

**Comment by mleary9** [comment]
![claimsmapping](https://user-images.githubusercontent.com/37228953/37286985-79c74406-25fb-11e8-94a7-5f3827391925.png)
Screen shot attached.

**Comment by Yvand** [comment]
I will look at your scenario more in detail and give you a feedback this week. 
Thanks

**Comment by mleary9** [comment]
Thank you Yvand.
I should mention, we are on SharePoint 2016 (16.0.4639.1002)

**Comment by Yvand** [comment]
Hi @mleary9, ok, now I actually have time to focus on this
Can you please:
- Set AzureCP logs in verbose:
```powershell
Set-SPLogLevel -Identity "AzureCP:*" -TraceSeverity VerboseEx
```
- repro the error
- Check SharePoint logs and filter on Product/Area "AzureCP"

**Comment by Yvand** [comment]
Looking at the code, I can make an assumption on the error: 
Did you register a claim type in the trust configuration, that is not registered in AzureCP claims mapping?
If so, and if some permissions were created with this claim type (before installing AzureCP), you should add this claim type in AzureCP claims mapping, it might fix the issue.

**Comment by mleary9** [comment]
Yvand,

Thank you for the information but I am still having issues, let me summarize every we did:

Configured Azure AD Trusted token provider with SharePoint 2013/2016. Tested the authentication by adding user to "user policy" on CA. everything worked. Removed the AzureAD users added previously from "User Policy" on CA. 

Installed the AzureCP, associated the AzureCP to SPTrustedIdentityTokenIssuer as per your documentation. Then created the App in Azure Active Directory per directions and granted the permissions to the App. 

Configured the AzureCP in SharePoint using the values from the Azure App (tenant name, Tenant id, App ID and secret) Matched the claims mapping in AzureCP. Here are the claims mapped for Azure AD. please see the attached screenshot.
![image](https://user-images.githubusercontent.com/37228953/37542745-9fd2dfd8-2935-11e8-8357-299754f90a95.png)

After doing all this when I try to look up name it will not resolve any names from Azure AD. I think the error we were getting before was because we did not remove the users that we had added prior to configuring AzureCP.

Please let us know if you need any additional information. By any chance  do we need to install Graph libraries on the SharePoint servers?

Here is the claims mappings in AzureCP and what we have mapped when SPTrusted provider is created.
![image](https://user-images.githubusercontent.com/37228953/37542924-3642733e-2936-11e8-9a93-1bea3a3ea070.png)
[Script-SPTrusted.txt](https://github.com/Yvand/AzureCP/files/1820712/Script-SPTrusted.txt)


Thanks,
Mike

**Comment by mleary9** [comment]
Yvand,

Thank you for all your help. We figured it out, the part of the problem was having users added before Azure CP installed. Everything works now....

Mike.
