### ISSUE TITLE
SharePoint Multi Tenancy with Azure AD

### ISSUE THREAD

**Issue by Kinumikao** [Yvand/AzureCP#140]
Hi Yvan,

Our scenario requires us to have multiple AAD Tenants on a single SP Farm each Tenant having their own Web Application. We already tried to get this working with MIM but unfortunately with no success. While researching the Issue I’ve read that AzureCP would technically Support Multi tenancy.

Could you give us any leads on how we could accomplish this?

Thanks in advance.

**Comment by Yvand** [comment]
Hi @Kinumikao, you won't be able to achieve the part "each Tenant having their own Web Application" using the standard version of AzureCP, but it should be possible if you [customize it](https://azurecp.yvand.net/docs/usage/for-developers/), although this requires strong SharePoint development skills.
Regarding the multi-tenancy part specifically, I don't know if/how it would work, I never tested it

**Comment by Kinumikao** [comment]
Hi Yvan, thanks for the quick reply.

Customizing AzureCP in terms of multi tenancy (multi auth provider and claim provider) sounds like a possibility for us. It is a crucial requirement for us. We have enhanced SharePoint development knowhow and are open to deep dive on that.

Is there a way we can have a short session with you to get a short exchange and introduction?

Many thanks in advance for your help.

**Comment by Yvand** [comment]
@Kinumikao I suggest you download [AzureCP.Developers.zip](https://github.com/Yvand/AzureCP/releases/tag/19.0.20210211.1285) and play with it in a dev environment (where OOB AzureCP is not installed).
I'll be happy to answer your questions / provide guidance if needed.
