### ISSUE TITLE
People Picker filter availability/configuration

### ISSUE THREAD

**Issue by bryanhart73** [Yvand/AzureCP#151]
We are long time LDAPCP users transitioning to AzureCP.  One of the features we use heavily in the LDAPCP environments is the "additional LDAP filter" values on each claim.  Is there an equivalent in AzureCP and/or another way to do this?

**Comment by Yvand** [comment]
@bryanhart73 no, with current design AzureCP will query your whole Azure AD tenant using the input of the user.
It might be possible to implement the same notion of filter, but Microsoft Graph is quite restrictive in the complexity of the queries it accepts and may reject one that contains such additional filter (currently, requests have some complexity to correctly manage guest/member users, and all possible user/group properties)
