### ISSUE TITLE
Question regarding attribute filter possibilities 

### ISSUE THREAD

**Issue by Kinumikao** [Yvand/AzureCP#152]
Hi @Yvand,

Is it possible with AzureCP to filter out Users with a specific User Attribute so that either only user with or without the specified attribute get shown in PeoplePicker? 

Many thanks for your help and kind regards,
Claudio

**Comment by Yvand** [comment]
hi Claudio. this is not possible unfortunately, for the same reason I mentioned in https://github.com/Yvand/AzureCP/issues/151#issuecomment-1108245335
