### ISSUE TITLE
Keep user metadata in sync

### ISSUE THREAD

**Issue by bartvermeersch** [Yvand/AzureCP#153]
Looking for some help or ideas on user metadata:

What is the best way to keep metadata (eg mail address, department) in sync (with Azure AD)?

If we include this info in our claims, is it also updated in the User Profile Service (when the values have changed)?

I read in another post that AzureCP can only set profiles properties in the site collections, where user is added for the 1st time in the site collection. I thought there was a timer job to keep the properties in the site collection in sync with the User Profile Service?

Thank you!

**Comment by RaZz85** [comment]
I'm also interested in the answer to this question, thank you for asking it!

**Comment by bartvermeersch** [comment]
Thank you for the info! 

Do you know when using hybrid profiles, is the UPS on-prem still in use and do we need to keep it up to date with PowerShell?

**Comment by bartvermeersch** [comment]
Merci! I'll let you know when we're that far ;-)
