### ISSUE TITLE
Post Successful login If I click on any link present on the site it gets redirected to login page - SP2016 AzureAD SSO AzureCP

### ISSUE THREAD

**Issue by samir07** [Yvand/AzureCP#157]
@Yvand - I have SP2016 multi server farm and configured it with AzureAD SSO, I have installed the Azure CP and SPBypassLoginPage solution as well, the issue I'm facing is, after the successful login to site, if I click on any of the link present on the site I get redirected to login page, I have a single server farm as well done the same configs there I don't see this issue, can you please help why this is happening? 
For installing Azure CP I have followed Safe method on multi server farm.

Your help is much appreciated, thanks.

**Comment by Yvand** [comment]
@samir07 there can be multiple causes for this issue. To identify what went wrong, you need to:
- Capture the HTTP traffic during authentication
- Identify the POST request to /_trust, when the browser sends the SAML token to SharePoint
- Identify the correlation ID of this request
- Filter the SharePoint logs on this correlation ID and inspect it to find what went wrong
