### ISSUE TITLE
Powershell script for configuring Azure CP

### ISSUE THREAD

**Issue by guptas-abhishek** [Yvand/AzureCP#16]
Hi Yvand,

 I had been using this lovely solution "AzureCP" from a long time for authentication via ACS.  After installing the wsp, had created Application in Azure AD to get Client ID , Client Secret etc and then creating a SPcustomidentityprovider  using powershell. In this new world of Azure AD authentication, slightly confused as in what to use and what not.....

Do you have any such documentation guiding step by step???

for example,  
Create a Enterprise Application in Azure AD
Create a Azure AD application 
Create a Custom Identity provider

But how to link it  is my problem at the moment??

**Comment by Yvand** [comment]
Hi @guptas-abhishek 
To establish the trust between SharePoint OnPrem and Azure AD, you can read [this article](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
To register the AzureCP app in Azure AD, you can read [this article](https://yvand.github.io/AzureCP/Create-App-In-AAD.html)

**Comment by guptas-abhishek** [comment]
This has been sorted, you can close this :) thanks a lot for the help
