### ISSUE TITLE
Having issues with SP2013 and  'System.Net.Http, Version=4.2.0.0'

### ISSUE THREAD

**Issue by ezmedia** [Yvand/AzureCP#160]
This is a great tool and will really help out my client.   Tried to push several versions of System.Net.Http into the GAC and have tried versions 17-20 of AzureCP.   Still cannot get rid of the error....

[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:   
 at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)    
 at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)

I have seen others with this issue but no clear solution.   Thanks for the help.

**Comment by Yvand** [comment]
@ezmedia I was very much hoping that v20 would fix this problem for good.
I spent a lot of time trying to understand why it occurs, but tbh I don't know what the cause is, only that somehow it affects a few machines and I was never able to reproduce it myself.
What version of .NET is installed on the SPS server? Can you try to update to [.NET 4.8.1](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net481)?

**Comment by ezmedia** [comment]
So I did another round of checking and discovered that my 2013 Dev box has 4.8.03761 and the AAD connection test works great.   The production farm is at 4.6.01950 and I get the File Not Found error when running the connection test.    I will push 4.8 to the farm today and test again.

**Comment by Yvand** [comment]
Then it might simply be caused by the [prerequisites](https://azurecp.yvand.net/docs/overview/introduction/#prerequisites) not met

**Comment by ezmedia** [comment]
Ok,  So that was the issue.    For all those who get this error here is your fix.   

I am running SharePoint 2013  Enterprise version 15.0.4571.1502.

Check the version of .net running on your server with this powershell:

` Set-Location ‘HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client’
 Get-ItemProperty -Path . | Select-Object Version`

If you get 4.6 as your current version then you will still get the 4.2 not found error.   

Here is a link to the stand alone 4.8 installer for lazy admins like myself.   Please install off hours as it will require a reboot.  SharePoint 2013 is supported on 4.8.  

[https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-8-offline-installer-for-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0](url)

Once completed AzureCP will run correctly.  Good luck!
