### ISSUE TITLE
SPuser profile missing claim atributes from AAD

### ISSUE THREAD

**Issue by saep202009** [Yvand/AzureCP#161]
We configured AzureCP claim provider for Sharepoint 2019 on premise. Both configuation AzureCP and Azure AD contains claims artibutes upn and emailaddress but in SP user profile after login to the SharePoint with AAD account is missing atribute emailaddress. Please help us fix this bug. See example of user details in AAD and in SPUserprofile.

![image](https://user-images.githubusercontent.com/70706181/200256663-1aa7eebf-3120-43a2-ad1d-1d4bd24849a1.png)

![image](https://user-images.githubusercontent.com/70706181/200257588-8ee6fad9-16ea-4d3a-9719-2d2e1fb1923b.png)

**Comment by Yvand** [comment]
SharePoint does not use (custom) claims providers to set the user profile properties in User Profile service, so AzureCP can not populate those entries.
AzureCP can only populate the user data in the site collection where the user is added.
This is due to SharePoint design, not a limitation of AzureCP

**Comment by ondrejtucny** [comment]
And how do we populate AzureCP can only populate the user data in the site collection where the user is added? This doesn't work either. We have four different environments, and two different Azure AD tenants, and no configuration worked so far. Any help or advice will be really greatly appreciated.

![image](https://user-images.githubusercontent.com/78753310/200419967-443c2740-b0c1-47c6-a760-00ca8f699ac4.png)
![image](https://user-images.githubusercontent.com/78753310/200420199-96a6d1c7-d418-47e2-bca8-728c1cace0d9.png)
![image](https://user-images.githubusercontent.com/78753310/200420325-21a06a35-0833-417c-9898-c07edb5a774b.png)
![image](https://user-images.githubusercontent.com/78753310/200420456-a795cbc4-0901-4886-82ff-898838337a4f.png)

**Comment by Yvand** [comment]
@ondrejtucny sorry for the delay I completely missed your message.
The configuration of AzureCP looks correct and I believe it does set the user metadata, but they are either ignored (user already exists in the site collection) or eventually overwritten by the UPA sync job which copies the data from the User Profile service to the site collection.
Does the ADFS user exist in the User Profile service, and if yes, are the properties set?

**Comment by Yvand** [comment]
@ondrejtucny sorry I did not pay attention to the screenshot. So it shows that the user profile of the AAD user does not have any data.
For this reason, whatever AzureCP does, SharePoint will always eventually overwrite it with the data from the user profile service.
To confirm this, you can test to delete the user profile, create a new site collection and add the user. You should see the user with the metadata populated (and not eventually overwritten)

**Comment by ondrejtucny** [comment]
@Yvand ok, let us test this hypothesis.

**Comment by saep202009** [comment]
> @Yvand I believe this is the screen shown on @saep202009 's original bug report. We both work on the same system. If I misunderstood your question, please let me know.
> 
> Currently, we are using some script to pull the missing data from AAD and write them into SPUser objects in individual sites. @saep202009 could you please share the script?

yes of course we use updated skript from this article and below is attached
https://www.sharepointdiary.com/2019/03/sharepoint-online-import-user-profile-property-from-azure-ad-using-powershell.html
[update_Email_DN.zip](https://github.com/Yvand/AzureCP/files/10077421/update_Email_DN.zip)

**Comment by saep202009** [comment]
Hi, Yvand, 
I deleted my UserProfile, created a new site collection and then I added (invited) myself as Reader to the collection. 
Sadly, the information of the user (work e-mail etc) has not appeared in the profile.

**Comment by Yvand** [comment]
@saep202009 then one thing you can do is to replay exactly this procedure, but this time with LDAPCP logs in VerboseEx:
`"LDAPCP:*"| Set-SPLogLevel -TraceSeverity VerboseEx`
Then you can check the logs and filter on Product/Area LDAPCP: LDAPCP records in VerboseEx the metadata it sets for each result it returns. This metadata is used by SharePoint to populate the profile properties in the site collection
