### ISSUE TITLE
AT Office LAN we are not getting USE token when user move from 1 page tp another page

### ISSUE THREAD

**Issue by gauravPOC** [Yvand/AzureCP#163]
This is something I repeatedly see in the ULS, but I don't think this is relevant to your custom page load. 
 
11/25/2022 14:58:44.32        w3wp.exe (HCLT-PC6297-1:0x4B28)        0x3054        SharePoint Foundation        Resolve        ax7no        Medium        Could not find idenitty for input. Input: 'i:0e.t|azuread|', Exception: 'System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.     at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)     at System.Security.Principal.NTAccount.Translate(Type targetType)     at Microsoft.SharePoint.Utilities.SPUtility.ResolvePrincipalInternalV2(SPWeb web, SPWebApplication webApp, Nullable`1 urlZone, String input, SPPrincipalEntityType types, SPPrincipalSource sources, SPUserCollection usersContainer, Boolean inputIsEmailOnly, Boolean alwaysAddWindowsResolver)'.        97047ca0-53fc-30fb-f50d-7063ef79faba
11/25/2022 14:58:44.32        w3wp.exe (HCLT-PC6297-1:0x4B28)        0x3054        SharePoint Foundation        Resolve        ax7nr        Medium        No match in user info list. Input : i:0e.t|azuread|.        97047ca0-53fc-30fb-f50d-7063ef79faba
11/25/2022 14:58:44.43        w3wp.exe (HCLT-PC6297-1:0x4B28)        0x3054        AzureCP        Claims Picking        1337        Unexpected        [AzureCP] Validation failed: found 0 entities instead of 1 for incoming claim with value '' and type '[http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn](https://apc01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fschemas.xmlsoap.org%2Fws%2F2005%2F05%2Fidentity%2Fclaims%2Fupn&data=05%7C01%7CGaurav-A%40hcl.com%7Ca5bdfb64bdc14e01a14308dad1acab7b%7C189de737c93a4f5a8b686f4ca9941912%7C0%7C0%7C638052836832613842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oilm4bw0WiByrsvjJFwLfpqKk2Gjv5rJUnQgDrEHEtU%3D&reserved=0)'        97047ca0-53fc-30fb-f50d-7063ef79faba

**Comment by Yvand** [comment]
@gauravPOC the exception occurs in method NTAccount.Translate(), so yes it is unlikely to be caused by AzureCP since no input coming from it should be treated as an AD account

**Comment by gauravPOC** [comment]
Thanks Yvan. So what would be the remedy for this?

Regards
Gaurav

**Comment by Yvand** [comment]
How do you repro this error? Does it have any impact on the site?

**Comment by gauravPOC** [comment]
Thanks Yvan. I have again read the log and something issue from NLB end. I am able to resolve the issue.

Thanks a lot for your help.

Regards
Gaurav
