### ISSUE TITLE
Change Property to display not working

### ISSUE THREAD

**Issue by julmsy** [Yvand/AzureCP#165]
Hello @Yvand,

I have another point that I have a strange behavior, but maybe I misunderstand it.

From the Claim types configuration table, I would like to change the Property to display for the main "User" mapping. Here is what I have after my initial configuration:
![image](https://user-images.githubusercontent.com/89072104/210336566-2dee7906-ec6b-49af-b107-1f3808d869dc.png)

All what I want now is to change the Property to display for the first line, because displaying the UPN is not really user friendly.
So I click on **Edit**, set **DisplayName** on the Property to display column:
![image](https://user-images.githubusercontent.com/89072104/210337111-1a3ceb9e-900c-4673-9b5a-d7a40e976493.png)

Then click on **Save**. But once the page is reloaded, the property set disappears...
![image](https://user-images.githubusercontent.com/89072104/210337420-7b840b02-95ef-41d0-bd9a-5a6cf35977e5.png)
No error message, and not found really interesting from the ULS logs.

I did a similar test with the http://schemas.microsoft.com/ws/2008/06/identity/claims/role claim type, where I changed the Property to display from DisplayName to Id, it works nice. So I don't understand why I cannot do the same for http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress claim type.

Is there something wrong?
Do I need to check something?

Let me know if you need more info.

Thanks!

**Comment by Yvand** [comment]
hello @julmsy, thank you for reporting this, I tested and I can reproduce the same issue.
I'll fix it, but in the meantime you can achieve the same in a different way:
Browse to central admin > AzureCP global admin page: In section "Display of user identifier results": Set the display name in the dropdown list

**Comment by julmsy** [comment]
Hello @Yvand ,
Thanks for the info and workaround. I did't paid attention to this setting. Work as expected with this option.

**Comment by julmsy** [comment]
For info if that could help someone, equivalent action in PowerShell:
```
Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")

$config.ClaimTypes[0].DirectoryObjectPropertyToShowAsDisplayText = "DisplayName"
$config.Update()
```

**Comment by Yvand** [comment]
@julmsy I fixed this issue in https://github.com/Yvand/AzureCP/pull/167, it was a dumb issue specific to the identity claim type, because it has a specific class (IdentityClaimTypeConfig) that inherits ClaimTypeConfig, and the code got the properties only of the child class.
