### ISSUE TITLE
AzureCP works in all web applications except central admin

### ISSUE THREAD

**Issue by grizzljt** [Yvand/AzureCP#17]
I am using AzureCP v12.Beta, version committed May 14

AzureCP does not return results from Central Administration.

From the 'Add users to this group' dialog, I see "Sorry, we're having trouble reaching the server."  From the Web Applications page -> User Policy -> Add Users -> 'Select People and Groups' dialog, I get the error "No results were found to match your search item.  Please enter a new term or less specific term.  This is true even when selecting 'Bypass Azure AD lookup' from the AzureCP configuration page.

These errors only exist in Central Administration, no other web application.

I see the following in ULS:

> [Forced due to logging gap, cached @ 05/10/2018 11:05:04.64, Original Level: Verbose] TenantAppEtag record requested but there is no sitesubscription or tenantId for site {0} so we will use the WebApp Id for the cache.

> [AzureCP] Unexpected error in FillSearch: System.ArgumentException: Exception of type 'System.ArgumentException' was thrown.  Parameter name: encodedValue, Callstack:   
>  at Microsoft.SharePoint.Administration.Claims.SPClaimEncodingManager.DecodeClaimFromFormsSuffix(String encodedValue)    
>  at azurecp.RequestInformation..ctor(IAzureCPConfiguration currentConfiguration, RequestType currentRequestType, List`1 processedClaimTypeConfigList, String input, SPClaim incomingEntity, Uri context, AzureADObjectType[] directoryObjectTypes, String hierarchyNodeID, Int32 maxCount)    
>  at azurecp.AzureCP.FillSearch(Uri context, String[] entityTypes, String searchPattern, String hierarchyNodeID, Int32 maxCount, SPProviderHierarchyTree searchTree)

> Claims Search call failed. Error Message: Object reference not set to an instance of an object.  Callstack:    at Microsoft.SharePoint.WebControls.PeopleQueryControl.IssueClaimsQuery(String searchPattern, String providerID, String hierarchyNodeID, Int32 pageSize, SPProviderHierarchyTree spgroupTree).

The Active Directory `spclaimprovider` was disabled via the following:

`$cpm = Get-SPClaimProviderManager`
`$ad = get-spclaimprovider -identity "AD"`
`$ad.IsVisible = $false`
`$cpm.Update()`

![image](https://user-images.githubusercontent.com/2603440/39837420-762de152-53a4-11e8-9a26-b1c4af0ef18e.png)

**Comment by grizzljt** [comment]
I downloaded the update, updated via Update-SPSolution, and manually ran IISRESET on all servers.

Unfortunately I am still unable to resolve from Central Admin and now I am unable to resolve from any Web Application.  The error has changed and is now:

> [AzureCP] Unexpected error while querying tenant '<TENANT GUID>': Microsoft.Graph.ServiceException: Code: BadRequest  Message: An identifier was expected
>  at position 16.    Inner error  , Callstack:   
>  at Microsoft.Graph.HttpProvider.<SendAsync>d__19.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
>  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    
>  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
>  at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__36.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
>  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    
>  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
>  at Microsoft.Graph.BaseRequest.<SendAsync>d__32`1.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
>  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    
>  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
>  at Microsoft.Graph.GraphServiceUsersCollectionRequest.<GetAsync>d__4.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
>  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    
>  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
>  at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()    
>  at azurecp.AzureCP.<>c__DisplayClass52_0.<<QueryAzureADTenantAsync>b__0>d.MoveNext()

I added the tenant as the GUID identifier and tried tenant.onmicrosoft.com as well as tenant.microsoftonline.com.   Once the other two tenant identifiers were added, the configuration page threw errors, see issue [18](https://github.com/Yvand/AzureCP/issues/18), but the change seems successful as the aforementioned error repeats with the three different identifiers.  Is there a way to clean this out and try again?

Thank you so much for this claim picker and the LdapCP.  You are truly a fantastic contributor to the SharePoint ecosystem.

**Comment by Yvand** [comment]
Ah yes, sorry I forgot to mention that you need to reset the claim types list after you updated AzureCP.
You have 2 options:
- central admin > AzureCP global settings page > "Reset AzureCP Configuration" (but that will also remove all tenants registered)
- PowerShell: run this script:
```powershell
Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")
$config.ResetClaimTypesList()
$config.Update()
```

Thank you very much for your feedback!

**Comment by grizzljt** [comment]
Thank you for the suggestion; I appreciate all your help!  I am still getting the same error after resetting the claim types list.  I also tried resetting the AzureCP configuration and starting from scratch with no change in behavior.   The error message is the same.

I am using the Tenant identifier GUID as the Tenant name in the 'Informations to add new Azure tenant' form.  This worked prior to the May 14 update.  I also tried tenant.onmicrosoft.com (domain status: available) and tenant.microsoftonline.com (primary domain).

**Comment by grizzljt** [comment]
I tried both of the following (individually) in addition to the GUID
TENANT.onMicrosoft.com
tenant.microsoftonline.com

Is there anything that needs to be done to the Enterprise App in Azure AD after upgrading the solution version?

The claims mapping looks good:

![image](https://user-images.githubusercontent.com/2603440/40007783-b652a8a6-576b-11e8-89cb-29c1eb98ab11.png)


Same error:

> [AzureCP] Unexpected error while querying tenant 'TENANT.onMicrosoft.com': Microsoft.Graph.ServiceException: Code: BadRequest  Message: An identifier was expected
>  at position 16.    Inner error  , Callstack:   
>  at Microsoft.Graph.HttpProvider.<SendAsync>d__19.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
>  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    
>  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
>  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()    
>  at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__36.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
>  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    
>  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
>  at Microsoft.Graph.BaseRequest.<SendAsync>d__32`1.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
>  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    
>  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
>  at Microsoft.Graph.GraphServiceUsersCollectionRequest.<GetAsync>d__4.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
>  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    
>  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
>  at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()    
>  at azurecp.AzureCP.<>c__DisplayClass52_0.<<QueryAzureADTenantAsync>b__0>d.MoveNext()
>

**Comment by Yvand** [comment]
Nope, claims mapping page is not good: look at the properties column: it shows numbers instead of actual property names.
That's the reason why you have this error (I changed the enum type that stores property names).
For some reason the reset of claim types configuration didn't work. Can you reset it again from claims mapping page and see if it works?

**Comment by grizzljt** [comment]
I swear I tried that before posting the error message but I just tried again anyway.  It works just fine now.  Sorry to waste your time!  Thank you so much for your help.
