### ISSUE TITLE
Deploy NuGet packages

### ISSUE THREAD

**Issue by pascalberger** [Yvand/AzureCP#173]
If AzureCP needs to be customized as documented on https://azurecp.yvand.net/docs/usage/for-developers/#when-azurecp-may-need-to-be-customized it would be nice to be able to consume AzureCP from a NuGet package.

**Comment by Yvand** [comment]
It is a fair point, I never thought about it and noone mentioned this before you.
The scenarios where a custom version of AzureCP is required are limited, but still for those it could make sense.
I planned to move the CI pipeline from Azure DevOps to GitHub, I'll keep your idea in mind when I'll work on that

**Comment by Yvand** [comment]
Done, package is available here: https://www.nuget.org/packages/Yvand.AzureCP/
