### ISSUE TITLE
Using Extension Attribute for Identity Claim

### ISSUE THREAD

**Issue by maryha** [Yvand/AzureCP#179]
Hi, I have a scenario where we are moving from ADFS on premises to Azure AD.  In the On Premises version, we used a custom LDAP attribute as the identity claim value, not userprincipalname.  We were able to configure the Ldapcp provider to use the custom Ldap attribute.  

In moving to Azure AD, we need to map to the same attribute that has been synced to an extention attribute in Azure AD.  We are able to select that extension attribute to send as the user identity value when configuring the Enterprise Application SSO SAML Claims.  But in the AzureCP configuration screens, we are not able to specify a custom attribute to search on to map to the user.  

I am assuming I need to modify the source code and create my own version of AzureCP to handle this case.  Is that right?

Thanks

**Comment by andikrueger** [comment]
Please have a look at this PR and the related issue: https://github.com/Yvand/AzureCP/pull/174 

This should be suitable for your requirement.

**Comment by maryha** [comment]
Hi @andikrueger, 

Yes! I think that is exactly what I needed.  Another question, though.  For the AD Connect Client ID, I have the GUID from one of the extension attributes (e.g. extension_ab22399ffg01144256feg_someuserid).  I tried putting that string into the AD Connect client ID field, but the extension attributes did not show up.  I will continue to debug, but is there a particular format that the client id needs to be in?

Thanks,
Mary

**Comment by andikrueger** [comment]
You need to use the full GUID of the AAD Connect Client in this format:  `93618954-57ab-4410-8972-6c815c136962` (example guid)
