### ISSUE TITLE
Issue on AzureCPSettings.aspx page

### ISSUE THREAD

**Issue by grizzljt** [Yvand/AzureCP#18]
I am using AzureCP v12.Beta, version committed May 14

When navigating to the page, I see the generic error:

> Object reference not set to an instance of an object. 

In the logs, the following is captured.

> Application error when access /_admin/azurecp/AzureCPSettings.aspx, Error=Object reference not set to an instance of an object.  
>  at azurecp.ControlTemplates.AzureCPGlobalSettings.PopulateFields()    
>  at azurecp.ControlTemplates.AzureCPGlobalSettings.Initialize()    
>  at azurecp.ControlTemplates.AzureCPGlobalSettings.Page_Load(Object sender, EventArgs e)    
>  at System.Web.UI.Control.LoadRecursive()    
>  at System.Web.UI.Control.LoadRecursive()    
>  at System.Web.UI.Control.LoadRecursive()    
>  at System.Web.UI.Control.LoadRecursive()    
>  at System.Web.UI.Control.LoadRecursive()    
>  at System.Web.UI.Control.LoadRecursive()    
>  at System.Web.UI.Control.LoadRecursive()    
>  at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

I added the tenant as the GUID identifier initially before the updated to the May 14th commit.  Once no results were returned from the claim picker, I added tenant.onmicrosoft.com as well as tenant.microsoftonline.com. Once the other two tenant identifiers were added, the configuration page threw the error shown above.  The configuration change seems to have applied.  Is there a way to clean this out and try again?

Sorry for the lack of helpful information.   =/

**Comment by Yvand** [comment]
I'm not able to repro that error, I don't know why it occurs.
I suggest you try to reset the configuration and add the tenants again. You have 2 options:
- If AzureCP global settings page works: click on "Reset AzureCP Configuration"
- Otherwise you can use PowerShell:
```powershell
Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [azurecp.AzureCPConfig]::ResetConfiguration("AzureCPConfig")
```

**Comment by grizzljt** [comment]
Thank you so much for your time and effort!  As per your other suggestion, I ran

```
Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")
$config.ResetClaimTypesList()
$config.Update()
```
The page now loads correctly. Those two PowerShell commands could be very helpful to others if placed on the debugging page (which seems to be missing on Github.io?).

**Comment by Yvand** [comment]
Great
It's new to v12, I'll update the documentation once v12 is RTM
