### ISSUE TITLE
Why does SharePoint 2016 on-prem FEDAUTH cookie expired after login?

### ISSUE THREAD

**Issue by lonnx** [Yvand/AzureCP#180]
Hello, I have a SharePoint 2016 on-prem environment configured to use Trusted Identity provider. It also hosts some web applications. After I successfully logged in, the FEDAUTH cookie expired as soon as it redirects to my web applications. I have SPSecurityTokenServiceConfig UseSessionCookies = true and BypassIdentityProviderForAppWebs = false. Thank you in advance. 

![image](https://user-images.githubusercontent.com/69867490/231654271-6a216f6a-f435-46b4-8aaa-dedf5f707bcf.png)

**Comment by Yvand** [comment]
@lonnx it is very difficult to point a specific cause with such a generic issue, but I would suggest to check the lifetime of the SAML token issued by your identity provider.
Please note that this issue has absolutely nothing to do with AzureCP, so I will close this issue
