### ISSUE TITLE
Nightly Release

### ISSUE THREAD

**Issue by julmsy** [Yvand/AzureCP#181]
Hello @Yvand,

I took some time today to test the Nightly release, but it seems that you provided a new version yesterday (20230419).
However this version seems to be... a step back?
There is no more option to add the extension attribute value in the tenant form to register:
![image](https://user-images.githubusercontent.com/89072104/233379588-52f7dcb1-dcf9-4cfb-be06-1840f942cdca.png)

Tested the WSP and also the source code that I compiled.
Could you please have a check ?

Thanks!

**Comment by Yvand** [comment]
hello @julmsy , it is unexpected, I'll check this and keep you posted

**Comment by julmsy** [comment]
@Yvand ok thanks, will test it!

**Comment by Yvand** [comment]
This is probably because you compile the `master` branch, which contains the latest published version.
All the changes not yet published are on `dev` branch, you should compile that one.
To set the version, you need to set the property `AssemblyFileVersion` in file `AssemblyInfo.cs`.

**Comment by julmsy** [comment]
Well, I took this one, so I expected to be the source code of the Nightly release:
![image](https://user-images.githubusercontent.com/89072104/233662243-f37859e1-c2b8-430d-ad14-e86cb99dc7be.png)

Is it not correct?

**Comment by Yvand** [comment]
Hmm yes it should, but I just checked and, indeed, it's not the expected version.
There is something wrong in my workflow, I think I understand what it is, I'll fix it next week and update this thread

**Comment by Yvand** [comment]
@julmsy I just fixed it, now all the assets, including the source code, are created using the expected commit

**Comment by julmsy** [comment]
Hello @Yvand
Many thanks! I'll time some time this week to test it.

**Comment by julmsy** [comment]
Ok, seems to be really better regarding the source code 😄 

Here are my few little remarks. I insist that they are non-blocking points, and do not interfere with the proper functioning of AzureCP.
- Just for info, there are two removed references of .snk:
![image](https://user-images.githubusercontent.com/89072104/234896087-e7eafb60-af14-4201-840b-6fcb9111c948.png)

- From Central Administration, there is a duplicate column 'Display name':
![image](https://user-images.githubusercontent.com/89072104/234897494-aff0dba0-0c71-485e-bd25-b60fbd749782.png)

- If I'm looking for an extension attribute, there are still a user reference. It could be a bit confusing in some situation.
For the example below, this BrandCode extensionattribute is the same for hundred/thousand of peoples behind. So there is no really reason that identity of someone appears here (same thing from Central Admin).
![image](https://user-images.githubusercontent.com/89072104/234901140-0feaff50-d124-4aaf-adb4-0f3c60795949.png)

Other than these remarks, all good!
Let me know if you would like to open a issue for one of these points, I'll do it.

**Comment by Yvand** [comment]
@julmsy regarding the extension attribute which shows a user value in the people picker, you can use the solution I mentioned in https://github.com/Yvand/AzureCP/pull/174#issuecomment-1441525027 to avoid it

**Comment by julmsy** [comment]
@Yvand ah yes very good point, I completely forgot this configuration.
So yes, all good with this solution.
Thanks to remind me this!

**Comment by Yvand** [comment]
And regarding the duplicated column 'Display name', it's a good point, actually I never noticed it.
But there is probably not much to do: AzureCP returns the 'Display name' just as it should, it's just too bad SharePoint duplicates it
