### ISSUE TITLE
Link to developer package throws 404

### ISSUE THREAD

**Issue by panjkov** [Yvand/AzureCP#183]
The source for azurecp.cs mentions that there is a developer package available to download from github. 

However, when I append filename "Azure CP Developers.zip" to the repo link and try downloading it, I receive 404.

**Comment by Yvand** [comment]
@panjkov indeed, I did not publish it yet for the new version, thank you for raising this.
I'll do it and update you when it is done

**Comment by Yvand** [comment]
@panjkov the package is now added the latest release: https://github.com/Yvand/AzureCP/releases/download/v21.0.20230703.25/AzureCP.Developers.zip

**Comment by panjkov** [comment]
Thank you @Yvand !

I will now close the issue.
