### ISSUE TITLE
Unable to test tenant connection

### ISSUE THREAD

**Issue by grizzljt** [Yvand/AzureCP#19]
I am using AzureCP v12.Beta, version committed May 14 (but this issue was noticed while using the may 4th commit).

Clicking test connection on the AzureCPSettings.aspx refreshes the page without any indication of a successful or failed test.  This behavior is repeatable on IE 11 and the latest version Google Chrome.

**Comment by Yvand** [comment]
Fixed in final [v12](https://github.com/Yvand/AzureCP/releases/tag/v12)
