### ISSUE TITLE
Role claim not working

### ISSUE THREAD

**Issue by oriolqc** [Yvand/AzureCP#2]
Role claim appears as missing from ACS provider, although it is configured.

**Comment by Yvand** [comment]
Hello, can you confirm that role claim type it is present in SharePoint trust, when you run cmdlet Get-SPTrustedIdentityTokenIssuer?

**Comment by oriolqc** [comment]
Thanks, the problem was I didn't add it. A little bit tricky by the way. This article was useful: http://samirvaidya.blogspot.com.es/2013/05/incoming-claim-types-do-not-include.html
