### ISSUE TITLE
Proxy Settings netsh winhttp show proxy

### ISSUE THREAD

**Issue by moojjoo** [Yvand/AzureCP#20]
For the PowerShell command > netsh winhttp show proxy I get "Current WinHTTP proxy Settings: Direct access (no proxy server).

With those results what instructions am I to follow? https://yvand.github.io/AzureCP/Configure-AzureCP.html

```
<system.net>
    <defaultProxy>
        <proxy proxyaddress="http://proxy.contoso.com:3128" bypassonlocal="true" />
    </defaultProxy>
</system.net>

`````
Thank you in advance, also small type on page - •SharePoine central administration site should be - •SharePoint central administration site

**Comment by cblomart** [comment]
Looks like netsh says you’re not behind a proxy.
If what he says is true I would figure you don’t need to set any proxy.

Cedric

Envoyé de mon iPhone

**Comment by moojjoo** [comment]
Sounds good!
