### ISSUE TITLE
Azurecp.wsp does not deploy

### ISSUE THREAD

**Issue by SDMcMillan** [Yvand/AzureCP#24]
When following the install instructions, I received an error "Claim provider with the name AzureCP does not exist."  When I followed a previous issue that was logged, I confirmed that wsp is not deployed.  I tried removing and redeploying with no success and have tried deploying through Central Administration and the manual deployment of the DLL suggested for servers not running SharePoint Foundation; none of which have been successful.  Central Administration shows Deploying, then not deployed when the job completes.  The Event Viewer and ULS logs record nothing for the deployment.  Any guidance would be greatly appreciated.  I am attempting to deploy version 11.

**Comment by Yvand** [comment]
How many servers do you have?
Does central admin run web application service?
On servers, can you check if you can find directories "AzureCP" and "AzureCP_Administration" in directory 15(/16)\TEMPLATE\FEATURES?

**Comment by SDMcMillan** [comment]
Hi Yvan,

I now have it deployed.

Thanks.
