### ISSUE TITLE
Users Suggestion not coming up

### ISSUE THREAD

**Issue by guptas-abhishek** [Yvand/AzureCP#27]
Hi,

After installing and integrating AzureCP with the AzureAD, the users are not able to get authenticated and neither I am getting any suggesions, but able to do a successful login. 
below is the sptrustedprovider output. Please suggest

PS C:\Users\Admin> Get-SPTrustedIdentityTokenIssuer

ProviderUri                   : https://login.microsoftonline.com/e4f2b803-7c85
                                -4de5-b1f1-ebc51c172212/wsfed
ProviderSignOutUri            :
DefaultProviderRealm          : urn:azureadtest.sercotest.com
ProviderRealms                : {}
ClaimTypes                    : {http://schemas.xmlsoap.org/ws/2005/05/identity
                                /claims/name, http://schemas.xmlsoap.org/ws/200
                                5/05/identity/claims/givenname, http://schemas.
                                xmlsoap.org/ws/2005/05/identity/claims/surname}
HasClaimTypeInformation       : True
ClaimTypeInformation          : {name, GivenName, SurName}
ClaimProviderName             : AzureCP
UseWReplyParameter            : False
UseWHomeRealmParameter        : False
GroupClaimType                :
RegisteredIssuerName          :
IdentityClaimTypeInformation  : Microsoft.SharePoint.Administration.Claims.SPTr
                                ustedClaimTypeInformation
Description                   : SharePoint secured by Azure AD
SigningCertificate            : [Subject]
                                  CN=Microsoft Azure Federated SSO Certificate

                                [Issuer]
                                  CN=Microsoft Azure Federated SSO Certificate

                                [Serial Number]
                                  78F11E8CBB478A8F4B03AA5C9647DBB8

                                [Not Before]
                                  3/6/2018 1:55:38 PM

                                [Not After]
                                  3/6/2021 1:55:37 PM

                                [Thumbprint]
                                  **********************************

AdditionalSigningCertificates : {}
MetadataEndPoint              :
IsAutomaticallyUpdated        : False
Name                          : AzureADwithMS
TypeName                      : Microsoft.SharePoint.Administration.Claims.SPTr
                                ustedLoginProvider
DisplayName                   : AzureADwithMS
Id                            : **************
Status                        : Online
Parent                        : SPSecurityTokenServiceManager
                                Name=SecurityTokenServiceManager
Version                       : 273014
Properties                    : {}
Farm                          : SPFarm Name=UAT2_Others_Config
UpgradedPersistedProperties   : {}

**Comment by Yvand** [comment]
Hi,
what version of AzureCP are you using?
Can you check SharePoint logs and filter on Product/Area "AzureCP" to get more information?

**Comment by guptas-abhishek** [comment]
Hi Yvand,   I have sorted this issue after reconfiguring SAML1.1 with Azure ad from scratch, so you can close this case....
