### ISSUE TITLE
AzureCP V12 not getting installed properly

### ISSUE THREAD

**Issue by guptas-abhishek** [Yvand/AzureCP#31]
Hi,
 I had been using AzureCP from a long time and recently when  I tried installing the latest version V12 of Azure CP,   I can't see it under get-spclaimprovider, thus cannot associate it with my TrustedIdentityprovider. But on the same server if  I try to install the old version of Azure CP (version 2) , it works perfectly fine.

is there any dependency or anything which  I need to install or to worry off??

**Comment by Yvand** [comment]
Hi, did you try to update from a previous version?
Do you have more information about the error that occurred?
Did you restore the old version of AzureCP by doing running Update-SPSolution, or by removing and installing it from scratch?

**Comment by guptas-abhishek** [comment]
Well.... yes Update solution has actually worked but sometimes uninstallation and reinstallation becomes a pain... Cheers Yvand.....
