### ISSUE TITLE
After upgrading to the last version

### ISSUE THREAD

**Issue by lexxus93600** [Yvand/AzureCP#33]
STS Call Claims Windows: Problem getting output claims identity. Exception: 'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Nito.AsyncEx, Version=4.0.1.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636' or one of its dependencies. The system cannot find the file specified.     at azurecp.AzureCP..ctor(String displayName)     --- End of inner exception stack trace ---     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)     at System.RuntimeType.CreateInstanceImpl(B...	801a829e-75fe-f0e2-76ac-a29cd08d3d3c
...indingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)     at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)     at System.Activator.CreateInstance(Type type, Object[] args)     at Microsoft.SharePoint.Administration.Claims.SPClaimProviderDefinition.CreateClaimProvider()     at Microsoft.SharePoint.Administration.Claims.SPClaimProviderManager.get_EnabledAndTrustedClaimProvidersByName()     at Microsoft.SharePoint.Administration.Claims.SPClaimProviderManager.<GetClaimProvidersByName>d__2.MoveNext()     at Microsoft.SharePoint.Administration.Claims.SPClaimProviderOperations.ClaimsForEntity(Uri context, SPClaimPr...	801a829e-75fe-f0e2-76ac-a29cd08d3d3c
...oviderOperationOptions mode, String[] providerNames, SPClaim entity)     at Microsoft.SharePoint.IdentityModel.SPSecurityTokenService.AugmentClaimsIdentityWithClaimProviders(SPRequestInfo requestInfo, IClaimsIdentity identity, SPClaim identityClaim)     at Microsoft.SharePoint.IdentityModel.SPSecurityTokenService.AugmentOutputIdentityForRequest(SPRequestInfo requestInfo, IClaimsIdentity outputIdentity)     at Microsoft.SharePoint.IdentityModel.SPSecurityTokenService.GetOutputClaimsIdentity(IClaimsPrincipal principal, RequestSecurityToken request, Scope scope)'.	801a829e-75fe-f0e2-76ac-a29cd08d3d3c

**Comment by Yvand** [comment]
I think you just need to recycle the w3wp running the SharePoint STS (not the site). Can you do that and check if it fixes the error?

**Comment by lexxus93600** [comment]
Yes, it works after recycling the w3wp.
Thank you so much !


________________________________
De : Yvan Duhamel <notifications@github.com>
Envoyé : Monday, August 6, 2018 3:51:24 PM
À : Yvand/AzureCP
Cc : lexxus93600; Author
Objet : Re: [Yvand/AzureCP] After upgrading to the last version (#33)


I think you just need to recycle the w3wp running the SharePoint STS (not the site). Can you do that and check if it fixes the error?
