### ISSUE TITLE
Feature request to help support Multi-Tenant scenarios

### ISSUE THREAD

**Issue by lunarridge** [Yvand/AzureCP#37]
We have started using this to support Multitenant deployments where each tenant has its own AzureAD Tenant for showing people to pick from, and at the moment we are making custom packages inheriting from the base AzureCP and overriding the CheckIfShouldProcessInput method to add a hardcoded filter against the context parameter.  This works great to limit the people pickers output based on the tenant url to just their AzureAD, but for every new tenant we bring on board, we need to create a new custom AzureCP with a *hardcoded URL* to filter by.  What I would like to ask for an upcoming version would be an additional data string field on the IAzureCPConfiguration so that we could actually pass in additional data from the settings UI, so then we could put in some JSON or simply the specific tenants URL in this case, and then we can use that in custom implementations versus hardcoding.  I realize I would still need to make custom packages for each tenant but I could then make AzureCPCustom01 - 50, deploy them all at once and deploy in a new farm and then our Ops guys just need to go in and configure each adding an extra bit of information (the url) as they bring new tenants online over time reducing our need to wait for outage windows (since deploying the hardcoded tenant version restarts the farm).

**Comment by Yvand** [comment]
If I understand, you want a custom field in the persisted object that you can use for your own needs.
What would be the type of this field?

**Comment by lunarridge** [comment]
That's it exactly... a simple String property for additional data would be perfect as then I can customize the settings UI to set it and read from it in the CheckIfShouldProcessInput to get the URL (or anything more complex I could parse it as JSON), and apply the filter.

**Comment by lunarridge** [comment]
It's not urgent, as we currently use the data hardcoded in each WSP and that does work.  It's more a matter of ops process improvement for us.  Whenever you update next would be fine, as knowing its coming at some point at least allows us to plan ahead.

**Comment by Yvand** [comment]
@lunarridge The release is now published: https://github.com/Yvand/AzureCP/releases/tag/14.0.20190307.660

**Comment by lunarridge** [comment]
Awesome.  Thanks so much, I will grab the latest and test it out in the next week or so.

**Comment by Yvand** [comment]
@lunarridge were you able to test if the new release fits your needs?
