### ISSUE TITLE
Hybrid Search does not support SAML based authentication

### ISSUE THREAD

**Issue by AussieDavo** [Yvand/AzureCP#38]
There is a limitation in Hybrid Search where any objects with SAML based permissions submitted to SharePoint Online Search index are security trimmed. 

This causes these SharePoint objects to be unsearchable when authenticating with AzureAD.

Reference (Hybrid Search supports Windows Claims only): https://blogs.msdn.microsoft.com/spses/2016/07/19/sharepoint-2016-hybrid-search-stuff-you-should-know-about-cloud-ssa/ 

Please vote to to make this a priority for the Microsoft product development team: https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365/suggestions/20037220-support-hybrid-search-on-premise-with-a-saml-authe

**Comment by Yvand** [comment]
Thank you for your comment, but I'm closing this issue as this is not the place for this
