### ISSUE TITLE
Azure AD users not recognized

### ISSUE THREAD

**Issue by VinceWeir** [Yvand/AzureCP#39]
I have installed AzureCP v13 on our on-prem SharePoint 2016 Farm. This installation seemed faultless, however when trying to add users to a site, the on-prem AD account is showing, and the Azure AD account is not showing in the people picker. In other words, I cannot select the correct Azure AD account (view attached screenshot).
![peoplepicker](https://user-images.githubusercontent.com/40571360/47219009-dae45480-d3ad-11e8-99b9-69f3f55edae7.jpg)

**Comment by Yvand** [comment]
Can you check logs and filter on Product/Area "AzureCP" to see what's going on?

**Comment by sikandersa** [comment]
Is there any resolution on this. I'm also facing the same issue. Except AD, Azure users are not appearing in AzureCP ? Any Help

**Comment by Yvand** [comment]
Same question as when the issue was raised:
Can you check logs and filter on Product/Area "AzureCP" to see what's going on?
