### ISSUE TITLE
An operation failed because the following certificate has validation errors:  Subject Name: CN=graph.microsoft.com 

### ISSUE THREAD

**Issue by joker-it** [Yvand/AzureCP#40]
Hello

we installed azurecp and we're very happy :) now we have a problem at one of our customer..
we use azurecp, after installation it works fine.. now after some weeks one of our SharePoint tools stops working..

in the uls log and in the eventlog i found this errors:

An operation failed because the following certificate has validation errors:  Subject Name: CN=graph.microsoft.com Issuer Name: CN=Microsoft IT TLS CA 2, OU=Microsoft IT, O=Microsoft Corporation, L=Redmond, S=Washington, C=US Thumbprint: 745AD3968D1CB3FB2B82950FA8855C16A4B30867  Errors:   NotTimeValid: A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.  .
**************************************************
[AzureCP] Unexpected error(s) occurred while querying Azure AD tenant 'asdasdasd.onMicrosoft.com':  [EXCEPTION 1]: System.Net.Http.HttpRequestException: An error occurred while sending the request.. Callstack:   
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    

i reset already the configuration of the azurecp, setup a new azure ad application.. but no luck.. 
any idea?

**Comment by Yvand** [comment]
hi @joker-it sorry for the late reply, did you resolve the issue?
It looks like Windows had a deprecated root/intermediate certificate, you may fix this by updating Windows

**Comment by Yvand** [comment]
Closing as unresponsive
