### ISSUE TITLE
azureCP do not contact the azure AD Application

### ISSUE THREAD

**Issue by mfu2019** [Yvand/AzureCP#41]
we ahve successfully installed azureCP on a Front end and deployed dll with powershell to backend SP2016 server running on azure Servers (SAAS).
we get addres from on prem but nothinh from AAD. we are using guest users and normal users in AAD. 
pleas hepl appeciated!

**Comment by mfu2019** [comment]
Sry for typos 
Help needed!

**Comment by Yvand** [comment]
@mfu2019 Can you check SharePoint logs and filter on Product/Area "AzureCP" to see what's wrong when AzureCP attempts to connect to Azure AD?

**Comment by Yvand** [comment]
@mfu2019 any update on this?
