### ISSUE TITLE
Can we migrate the questions and solutions raised in codeplex?

### ISSUE THREAD

**Issue by kmdabubakar** [Yvand/AzureCP#46]
Hello All,
I am an issue related to people picker search which is using Azure AD. I found related questions in discussions section of CodePlex version but I cannot see the answers there.
Click of any link will keep you on the same page and it is saying that the 'This project migrated to https://github.com/Yvand/AzureCP'.
I checked the issues in Git hub, but did not get the questions which was raised in CodePlex version.
Can we migrate those questions here as well? Or where else I can get the answers in Git Hub version?

**My Issue:**
If I am searching for Azure AD users in SharePoint people picker, it is saying 'no result found'. I can resolve on 'Ctrl+K'.

Thanks in advance.
![image](https://user-images.githubusercontent.com/46310646/50581971-9df40e00-0e84-11e9-9fbc-f86dc6b60a61.png)

**Comment by Yvand** [comment]
@kmdabubakar I cannot migrate the questions from Codeplex.
But to troubleshoot your issue, can you filter SharePoint logs on Product/Area "AzureCP" and check the output?

**Comment by Yvand** [comment]
Closing as unresponsive
