### ISSUE TITLE
Question: Authenticatin against multiple Azure AD directories

### ISSUE THREAD

**Issue by vargasfe** [Yvand/AzureCP#47]
I have installed and tested AzureCP to authenticate a single SP WebApp against a single Azuer AD.
The questions are:
1. how to install and configure AzureCP to authenticate a SP WebApp against multiple Azure AD directories.  For example I may have users from two or more partner companies logging in to my SP Web App.

2. How to install and confiure AzureCP to authenticate multiple SP WebApps, each against a different set of Azure AD directories.  For example, I can share WebApp-A with AzureAD-1 and AzureAD-2, and then share WebApp-B with AzureAD-3 and AzureAD-4, where both WebApps are in the same farm.

Thanks,

**Comment by Yvand** [comment]
About 1: in central admin > Security > AzureCP config you can add as many Azure AD tenants as you need
About 2: this is not possible with the standard version. To implement this, you must download ["AzureCP.Developers.zip"](https://github.com/Yvand/AzureCP/releases) and create your own unique claims provider, that inherits AzureCP. This requires SharePoint development skills.

**Comment by Yvand** [comment]
Setting up multiple Azure AD is the same as 1 Azure AD tenant, you just need to set them in AzureCP configuration
To troubleshoot why it doesn't work, check ULS logs and filter on Product/Area "AzureCP"

**Comment by Yvand** [comment]
Closing as unresponsive
