### ISSUE TITLE
Change User identifier property using PowerShell

### ISSUE THREAD

**Issue by AussieDavo** [Yvand/AzureCP#49]
Hi Yvand,

Is it possible to change the "User identifier for 'Guest' users" setting in the global configuration of AzureCP using PowerShell?

![image](https://user-images.githubusercontent.com/5260349/52978506-5ec25200-341d-11e9-9a1f-f6fa1e363826.png)

I am working on a PowerShell script to switch the User Identifier to Mail then add the user using the mail attribute to the site collection, once complete then switch the User Identifier back to UserPrincipalName.

I am able to switch the User Identifier to Mail by running the following PowerShell to reset the claims config:
`Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")
$config.ResetClaimTypesList()
$config.Update()`

However I am unsure on how to change it back to UserPrincipalName using PowerShell.

This will assist me in allowing Guest users from other O365 tenancies into my SharePoint on-prem whilst still allowing Guest users with Windows Live accounts.

**Comment by Yvand** [comment]
Hi @AussieDavo you can use method ClaimTypeConfigCollection.UpdateIdentifierForGuestUsers():

```powershell
Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")
$config.ClaimTypes.UpdateIdentifierForGuestUsers([azurecp.AzureADObjectProperty]::UserPrincipalName)
$config.Update()
```
