### ISSUE TITLE
ClaimProviderName

### ISSUE THREAD

**Issue by abrmed** [Yvand/AzureCP#5]
Hi Yvand;
i'm trying to install AzureCP, and when I type this command:
$trust = Get-SPTrustedIdentityTokenIssuer "NAME"
$trust.ClaimProviderName = "AzureCP" 
i got the error:
Exception setting "ClaimProviderName": "Claim provider with name AzureCP does not exist."

Any idea Please :( ??

**Comment by Yvand** [comment]
hi @abrmed, can you run this cmdlet below and confirm if AzureCP is listed?
```powershell
Get-SPClaimProvider | ft DisplayName
```

**Comment by abrmed** [comment]
Hi Yvand,
Thank you for the email, after lunching the command got:

DisplayName
-----------
System
Active Directory
All Users
Forms Auth
User Profile Claim Provider

Regards

2017-11-22 4:16 GMT-05:00 Yvan Duhamel <notifications@github.com>:

**Comment by Yvand** [comment]
Hi @abrmed, this means that for some reason AzureCP is not installed on the farm.
Do you see AzureCP solution in farm solutions?
Do you see AzureCP feature activated in farm features?

**Comment by abrmed** [comment]
Hi Yvand,
Thanks for the replay, I reinstalled AzureCP.wsp and after that all it's
ok. Now, when i tried to add new Tenant in Central Administration, after
typing the information and test tenant connecton get this error:
Unable to connect to Azure tenant
It may be expected if w3wp process of central admin has intentionally no
access to Azure.
One or more errors occurred.
Error detail: 'authority' should be in Uri format Parameter name: authority


???

2017-11-23 10:07 GMT-05:00 Yvan Duhamel <notifications@github.com>:

**Comment by Yvand** [comment]
hi @abrmed 
did you follow instructions on https://yvand.github.io/AzureCP/Create-App-In-AAD.html to create the app and fill required information in AzureCP?
Yesterday I publised a new version, it contains many improvements, please make sure to download it in https://yvand.github.io/AzureCP/ and follow instructions in https://yvand.github.io/AzureCP/Update-AzureCP.html to update AzureCP
