### ISSUE TITLE
How to find the Application secret

### ISSUE THREAD

**Issue by sav169** [Yvand/AzureCP#51]
I am going through - https://yvand.github.io/AzureCP/Register-App-In-AAD.html
below section
----------------
•Click on Keys: In “Password” section type a key description (e.g. “AzureCP for SP”), choose a Duration and Save. 
Note: “Password” corresponds to the “Application Secret” in new tenant form in AzureCP.
-----------------

I don't see "Keys" in the enterprise application in Azure.
can you help me where to find this

**Comment by Yvand** [comment]
@sav169 
In the current "App registrations" tab: link is "Keys"
In the "App registrations (Preview)" tab: link is "Certificates & secrets". Here you can generate a new secret

**Comment by sav169** [comment]
Thanks , I was able to generate the secret. The connection to the tenant was successful.
Now when I browse to the site and try to give permission to any user, it says "no result found". It cant find any user.

**Comment by Yvand** [comment]
You can get more information about this issue by checking the SharePoint logs and filtering Product/Area on "AzureCP"

**Comment by sav169** [comment]
Thanks for the response. In uls it says the below
----------------------
[AzureCP] There is no Azure tenant registered in the configuration 'AzureCPConfig'. Visit AzureCP in central administration to add it, or override method GetConfiguration.
-----------------------
I have followed your article and the test connection to tenant from central admin says successfully connected. is there any thing I am missing

**Comment by Yvand** [comment]
Did you click "Add tenant" to actually add the tenant to the list?

**Comment by sav169** [comment]
Thanks! It was not added. I have now added it. The ULS log now shows permissions error when I try to add user permissions.
-------------------
[AzureCP] Unexpected error(s) occurred while querying Azure AD tenant 'mycompany.onMicrosoft.com':  [EXCEPTION 1]: Microsoft.Graph.ServiceException: Code: Authorization_RequestDenied  Message: Insufficient privileges to complete the operation.    Inner error  . Callstack:   
 at Microsoft.Graph.HttpProvider.<SendAsync>d__19.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    

--------------------

**Comment by Yvand** [comment]
Did you grant the permission **exactly** as documented in https://yvand.github.io/AzureCP/Register-App-In-AAD.html ?

**Comment by sav169** [comment]
Thanks. This has been resolved.

**Comment by sav169** [comment]
Thanks! this is now working and is a great way to add new Azure AD user permissions. Howevere, we have existing site collection with hundreds of existing AD users. Is there a way to convert the existing AD users to Azure AD users ? This way we can avoid adding same users again. Any pointers would be usefull.
Thanks!!

**Comment by Yvand** [comment]
@sav169 migrating users from Windows to Trusted is possible but it has many impacts, so it must be very carefully tested before it is run in production.
In a nutshell, you migrate each user individually like this;

```powershell
$oldlogin="i:0#.w|contoso\user1";
$newlogin="i:05.t|contoso.local|user1@contoso.local";
[Microsoft.SharePoint.Administration.SPFarm]::Local.MigrateUserAccount($oldlogin, $newlogin, $false);
```

This will migrate Windows user "user1" to the trusted authentication mode in the whole farm
