### ISSUE TITLE
Group membership doesn't calculate for Office groups (Unified groups/O365 Groups)

### ISSUE THREAD

**Issue by joshtransient** [Yvand/AzureCP#52]
Running v13 on SharePoint 2016.

Added an Office 365 Group (Unified Group) to any ACL (item, list, site, web app policy), and no one who is a member of that group can access the resource. Security groups work fine, but figured that since SPO can handle O365 Groups, then maybe on-prem can, as well.

After enabling verbose logging, I discovered that AzureCP only augments a claim with groups that are security-enabled. Fortunately, I had enough permissions on my Azure tenant to do this:

    $group = Get-AzureADMSGroup -SearchString 'name of group'
    Set-AzureADMSGroup -Id $group.Id -SecurityEnabled:$true

Once I security-enabled the group, AzureCP started picking up that group in claims augmentation.

Not sure how this should be handled moving forward...allow filtering of non-security-enabled groups? Flag non-security-enabled groups with a prefix/suffix? Just a documentation update?

**Comment by Yvand** [comment]
It's a great question.
The reason why AzureCP does not return O365 groups is that when it gets group membership of the user, it sets "securityEnabledOnly: true", which excludes them.
I tested with the [Graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) to set "securityEnabledOnly: false" and it includes O365 groups as you would expect.

So I can change the code to retrieve them, or make this customizable by the administrator.
What do you think?

**Comment by joshtransient** [comment]
On v13, my People Pickers return all groups (including the O365 Groups) when I add the _role_ claim type to my TrustedIdentityTokenIssuer. Hence the reason the issue was opened...didn't know if it was SharePoint not calculating group membership, or if the group not being security-enabled caused the disconnect :)

IMHO, a switch on the global configuration page allowing non-security-enabled groups to autocomplete/resolve might be best, with a blurb mentioning "O365 groups must be security-enabled, etc" on the control.

Thanks for being willing to chat about this!

**Comment by Yvand** [comment]
@joshtransient sorry I didn't come back to you earlier on this topic.
I've been looking at this, and, as you suggested, I'll add an option in global config page to choose if only securityEnabled groups should be returned. I think it it should be set to true by default.
Please let me know if you have comments/suggestions on this.

**Comment by joshtransient** [comment]
@Yvand sincerely appreciate it, my dude.

**Comment by Yvand** [comment]
@joshtransient last week I published a pre-release that includes this improvement: https://github.com/Yvand/AzureCP/releases/tag/15.0.20190621.906
Are you able to test it and let me know if it fits your needs?
