### ISSUE TITLE
https://yvand.github.io/AzureCP/Register-App-In-AAD.html need an update

### ISSUE THREAD

**Issue by abdulhafizmmuallah** [Yvand/AzureCP#53]
Hi, from my checking Azure AD already updating their interface therefore steps for above article is not working anymore. Could you please provide us with the latest steps based on the new interface of Azure AD?

Thank you!

**Comment by Yvand** [comment]
Hi @abdulhafizmmuallah, thank you for reporting this, indeed the interface changed quite significantly.
I'll upate the documentation and report here when it's done.

**Comment by Yvand** [comment]
Finally I just updated the page https://yvand.github.io/AzureCP/Register-App-In-AAD.html to match the new UI in the Azure portal
