### ISSUE TITLE
Issue in powershell with $config when configuring AzureCP

### ISSUE THREAD

**Issue by mjones0204** [Yvand/AzureCP#54]
I am having an issue in powershell when trying to configure AzureCP.  I have it installed and deployed in this single server farm and have verified the dll is in the gac.  Server has been rebooted after install.

When I issue the powershell command: 
$config = [azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")

Nothing is being returned as when I type in $config or $config.ClaimTypes, nothing is shown.

Any ideas on what I am doing wrong?

**Comment by Yvand** [comment]
That is because you need to explicitly load AzureCP assembly first:

```powershell
Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
```
