### ISSUE TITLE
SharePoint 2010 AzureCP

### ISSUE THREAD

**Issue by sabeehsharif** [Yvand/AzureCP#55]
Hi,

How i can use AzureCP with SharePoint 2010?

**Comment by Yvand** [comment]
Not as-is, as AzureCP is compiled for .NET 4.5, which is not supported by SharePoint 2010.
If you wish to use it on SharePoint 2010, you will have to compile the source code yourself for this version.

**Comment by sabeehsharif** [comment]
Thanks. 
Can you please give me a way to implement this for SharePoint 2010? 
i am thinking to implement using Direct Graph API call is it possible?
