### ISSUE TITLE
Azure AD Graph API Query

### ISSUE THREAD

**Issue by sabeehsharif** [Yvand/AzureCP#56]
Can you please give me a way to implement this for SharePoint 2010?
i am thinking to implement using Direct Graph Rest API call is it possible?

**Comment by Yvand** [comment]
AzureCP is free and open source.
You can fork the project, get the source code and make all necessary changes to the project so that it works with SharePoint 2010. I don't know if it will be simple or not, as I don't know what APIs are missing in .NET 3.5
