### ISSUE TITLE
Check Permissions SharePoint for Auzre AD groups

### ISSUE THREAD

**Issue by sabeehsharif** [Yvand/AzureCP#57]
Thanks for the great way out i have implemented this for SharePoint 2010 but facing issue regarding Check Permission SharePoint.

1: Check Permissions functionality is implemented in this Azure CP code for Azure AD groups? 
Like in which security group user belong. but keeping in mind Security group have Azure AD group to traverse users.

**Comment by Yvand** [comment]
Check Permissions functionality uses a token that is valid for 24h, and bound to the current site collection.
If you wish to test it in a reliable way, you should either:

- Test it in a new site collection
- Or lower its lifetime to 1 min using the cmdlet below:

```powershell
$cs = [Microsoft.SharePoint.Administration.SPWebService]::ContentService
# Default value:   New-TimeSpan -Days 1
$cs.TokenTimeout = New-TimeSpan -Minutes 1
$cs.Update()
```

**Comment by sabeehsharif** [comment]
For Check Permissions which functions called from SPClaimProvider class?

**Comment by Yvand** [comment]
It will call either one of the AzureCP.FillClaimsForEntity() methods
