### ISSUE TITLE
Duplicate users with  same email with different display name

### ISSUE THREAD

**Issue by DilaFernan** [Yvand/AzureCP#59]
I have configured azureCP with sharePoint 2013 following below [reference](https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial). But when users are adding to sharepoint user group, its giving me error saying "user does not exist or not unique". 
![image](https://user-images.githubusercontent.com/52557819/60699656-86204400-9f12-11e9-9f77-a28b55b4ba50.png)
Further I can see  that user with same email address is resolved with only their surname.
![image](https://user-images.githubusercontent.com/52557819/60699785-08a90380-9f13-11e9-8d12-32ca3fb05c2d.png)
(shows only surname above)
![image](https://user-images.githubusercontent.com/52557819/60699940-9f75c000-9f13-11e9-9465-0151742125df.png)
This user with same email but display name differ.

Note: this exception only for some of the users on AD and some are working as expected.
Appreciate help.

**Comment by Yvand** [comment]
Can you check SharePoint logs and filter on Product/Area "AzureCP" while you reproduce the issue, to see AzureCP does?

**Comment by DilaFernan** [comment]
Thanks Yvand for the response.

These are the log entries found.
![image](https://user-images.githubusercontent.com/52557819/60783432-3f2b8c00-a168-11e9-9789-b22786263ec1.png)

as per logs for the user hdi, 0 users returns , but i can see results on people picker. Really appreciate if you can give me a clue. why is this happening. And also there is a valid user on Azure Ad with the email address hdi@xxxxxx.com.

**Comment by Yvand** [comment]
Clearly AAD does not return any user from the query sent by AzureCP.
If you want to understand why, you may configure Fiddler as a proxy in the web.config of the site, to capture the traffic between AzureCP and AAD and see the exact query sent by AzureCP.

The change to make in the web.config is very similar to the proxy configuration described [here](https://yvand.github.io/AzureCP/Configure-AzureCP.html).

**Comment by DilaFernan** [comment]
Thanks for the guidance. 
After seen the query passes to AAD ((UserPrincipalName eq 'hdi@xxxxx.com' and UserType eq 'Member') ), figure out that, some users which are giving error "user does not exist or not unique " do not have the user type property populated.   Now i want to find a solution to validate selected user from suggestions list  while resolve before hitting share button to avoid that exception.

The duplicate result is another issue separate from this , it happens when you search from surname , it populates a list of users only with surname as display name. when you have many users with same surname get confused to see many duplicates. 

![image](https://user-images.githubusercontent.com/52557819/61018877-df2a2500-a3b5-11e9-9c36-3057505b9b53.png)

any suggestions here please.

**Comment by Yvand** [comment]
About validating before sharing, sorry it's not clear what exactlu you want to do, and on for which reason.

About the duplicates, I guess it's because all those users have the same surname. The only solution is to select a property that does not have such duplicates.

**Comment by Yvand** [comment]
Closing this since it's inactive, feel free to reopen if needed
