### ISSUE TITLE
Error when configuring AzureCP with powershell

### ISSUE THREAD

**Issue by sesellis** [Yvand/AzureCP#63]
Hello, I'm trying to run the powershell script to configure AzureCP provided here: https://yvand.github.io/AzureCP/Configure-AzureCP.html 

I get the following error when running the powershell: "The property 'EnableAugmentation' cannot be found on this object. Verify that the property exists and can be set."

I believe I have followed the installation steps correctly, however when I run the SQL included on that page (SELECT Id, Name, cast (properties as xml) AS XMLProps FROM Objects WHERE Name = 'AzureCPConfig') it returns 0 rows--is that related?

Here is the complete error from PowerShell:

The property 'EnableAugmentation' cannot be found on this object. Verify that the property exists and can be set.
At C:\temp\azurecpconfig.ps1:9 char:1
+ $config.EnableAugmentation = $true
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

You cannot call a method on a null-valued expression.
At C:\temp\azurecpconfig.ps1:10 char:1
+ $config.Update()
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\temp\azurecpconfig.ps1:13 char:1
+ $config.ResetClaimTypesList()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\temp\azurecpconfig.ps1:14 char:1
+ $config.Update()
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\temp\azurecpconfig.ps1:17 char:1
+ $config.ResetCurrentConfiguration()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\temp\azurecpconfig.ps1:18 char:1
+ $config.Update()
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\temp\azurecpconfig.ps1:25 char:1
+ $config.AzureTenants.Add($newAADTenant)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\temp\azurecpconfig.ps1:26 char:1
+ $config.Update()
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\temp\azurecpconfig.ps1:33 char:1
+ $config.ClaimTypes.Add($newCTConfig)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\temp\azurecpconfig.ps1:34 char:1
+ $config.Update()
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\temp\azurecpconfig.ps1:37 char:1
+ $config.ClaimTypes.Remove("ClaimTypeValue")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\temp\azurecpconfig.ps1:38 char:1
+ $config.Update()
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by Yvand** [comment]
@sesellis It looks like the AzureCP.dll assembly is somehow not in the GAC, can you double check this?

**Comment by dvanboven** [comment]
I've got the same issue and when I try to add the (again) .dll assembly in the GAC, I receive the following message:

Assembly AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636 sucessfully re-added to the GAC

**Comment by Yvand** [comment]
- Did you restart PowerShell after you updated the assembly in the GAC?
- What version did you download?
- In "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\AzureCP\v4.0_1.0.0.0__65dc6b5903b51636\AzureCP.dll" > Properties > Details: what is the version?

**Comment by dvanboven** [comment]
I'm so sorry for the delay ...

Below the answers on your question:
- yes, I've restarted PowerShell (even the whole server)
- the latest version: https://github.com/Yvand/AzureCP/releases/download/16.0.20200303.1092/AzureCP.wsp
- file version: 16.0.15215.1092 and product version: 16.0.20200303.1092

**Comment by Yvand** [comment]
@dvanboven for some reason the configuration object of LDAPCP was not created.
Can you visit LDAPCP global configuration page in central administration > security? It should immediately create it.

**Comment by dvanboven** [comment]
Excellent, that was the trick! It works now 👍
