### ISSUE TITLE
Certificate based authentication in Azure AD

### ISSUE THREAD

**Issue by sergey-tihon** [Yvand/AzureCP#64]
Current version of `AzureCP` uses `ApplicationSecret` to authenticate in Azure AD and acquire `AuthenticationHeader` for MS Graph.

```Powershell
# Add a new Azure AD tenant
$newAADTenant = New-Object azurecp.AzureTenant
$newAADTenant.Name = "xxx.onMicrosoft.com"
$newAADTenant.ApplicationId = "Application ID"
$newAADTenant.ApplicationSecret = "XXX"
$config.AzureTenants.Add($newAADTenant)
$config.Update()
```

Azure AD application page states

> For a higher level of assurance, we recommend using a certificate (instead of a client secret) as a credential.

Is there a way to use `certificate`-based authentication with `AzureCP`?

**Comment by Yvand** [comment]
AzureCP does not not support certificate-based authentication, but it can be considered for a future version, thanks for the suggestion

**Comment by Yvand** [comment]
@sergey-tihon I know it's been a while but today I started working on this.
I [committed changes](https://github.com/Yvand/AzureCP/tree/implement-cert-authN) to support this scenario, it still needs work but it's working in my test box and it will be ready for the next version.
Please let me know if you have any comment about this.

**Comment by sergey-tihon** [comment]
Thank you for you work @Yvand !
I quickly take a look on changes and don't fully understand how installation of AzureCP + cert auth will look like ...
https://github.com/Yvand/AzureCP/compare/implement-cert-authN

Current code use hardcoded  `ClientCertificatePrivateKeyPassword`, this is probably covered by `it still needs work` 😊

1. How do you see installation guide? (what admin will have to do to configure cert auth)
1. Are you sure that Exportable certificate and private key stored in SharePoint is the best option?

Not sure how to easily do it on all  WFE at once, but it should be possible to
- `Import-PfxCertificate -CertStoreLocation Cert:\LocalMachine\My ...` (on all machines)
- Grant access to use private key only for specific account (that are used for  IIS app pools)
- Every time when we need cert - extract it from store by thumbprint.

p.s. I did similar setup for [cert-based authentication in Vault](https://sergeytihon.com/2019/10/08/hashicorp-vault-and-tls-certificate-authentication-for-net-applications-comprehensive-guide/)

**Comment by Yvand** [comment]
@sergey-tihon I am happy to discuss the security concerns and determine the best implementation, I have much to learn on this area.

While using the Windows certificate store is technically feasible, it has significant drawbacks:

- The administrator must ensure that the certificate is present in all SharePoint servers, with proper permissions.
- The list of accounts that need access to the private key is potentially large: all SharePoint processes may use AzureCP, and not only: PowerShell scripts may also use AzureCP (through SharePoint API). It makes such a list hard to maintain, especially across multiple machines.

Considering this, I decided to store the private key in the persisted object that holds AzureCP configuration. The benefits are:

- Setting/updating the certificate is centralized and super easy: the admin just needs to give the certificate to AzureCP.
- Currently, yes it uses a hardcoded password, but the level of security is strictly the same as it is today with the client secret, which is stored in clear text in the configuration database.

With that said, I realize it's bad to use a hardcoded password to store a private key, but I'm not an expert on security and I don't know how to use a secure password that does not depend on the machine or the account. Maybe using the SharePoint passphrase could be an option, I can dig in this area. Do you have any suggestion?

**Comment by sergey-tihon** [comment]
What do you think about storing secrets inside `Secure Store Service`?
> [The Secure Store Service is a claims-aware authorization service that includes an encrypted database for storing credentials.](https://docs.microsoft.com/en-us/sharepoint/administration/secure-store-service-planning)

Drawback: One more dependency and more complicated configuration.
Benefit: Secure encrypted storage to secrets provided by SharePoint.

https://social.technet.microsoft.com/wiki/contents/articles/20110.sharepoint-retrieving-credentials-from-the-secure-store-application-using-c.aspx (never use it before)

**Comment by Yvand** [comment]
In theory it's the perfect solution, in practice, it makes the configuration and the implementation significantly more complex.
Besides, from my experience the Secure Store is not commonly used, so it would also require a particular effort to document how to properly configure it for AzureCP, including the maintenance (update the secret).
It also creates a very significant dependency: if for some reason Secure Store stops working, AzureCP also stops working, which would be pretty bad.

On my side I investigated if I can use somehow the SharePoint passphrase to encode/decode a secret. Short answer is no, no public API allows it.
I tried using reflection to call internal method Microsoft.SharePoint.Administration.SPCredentialManager.EncryptWithApplicationCredentialKey() but I got a "SPException: Cannot retrieve the information for application credential key".

**Comment by sergey-tihon** [comment]
Then I prose to store certificate and `ClientCertificatePrivateKeyPassword` the same way as you stored `ApplicationSecret` and open new issue `Implement Secure Secret Store` for refactoring that will encrypt all secrets or more them in secure place. This should not postpone `V16` release.

**Comment by Yvand** [comment]
You mean to keep the current implementation as-is for v16, and plan the implementation of the Secure Store for a future version?
