### ISSUE TITLE
Can not update picker data in the AZURECP - ClaimTypesConfig.aspx page

### ISSUE THREAD

**Issue by totayo1000** [Yvand/AzureCP#65]
Hi 

I am trying to update the field PickerEntity metadata field but each time i hit save it gets back to empty 

Thanks for your help 

Regards
![Capture](https://user-images.githubusercontent.com/55228538/64770705-9c1b3800-d545-11e9-9f06-7bd81e8be96a.PNG)

**Comment by Yvand** [comment]
This is not an error, just a call stack of AzureCP updating its persisted object, which is expected since it holds the configuration

**Comment by totayo1000** [comment]
Thanks for the clarification.. i guess there is an issue with the GUI i will try doing it through the powershell

**Comment by totayo1000** [comment]
Hi again updating using powershell is not providing the desired effects .. i guess there is an issue with the from ,because doing the same update on the level of the group is working normally .. appreciating in advance  your help in advance as i am really stuck with  user emails not populating

**Comment by Yvand** [comment]
@totayo1000 sorry I completely forgot to follow up this issue. Did you make progress on it?

**Comment by totayo1000** [comment]
hi yvand, glad to hear from you,  i am still stuck  as i tried all fields not only email and got the same result ... currently as a workaround i am adding manually the email to key users profiles .. i know it is not a solution but hoping the form issue will be resolved soon

**Comment by Yvand** [comment]
@totayo1000 can you switch AzureCP logs to VerboseEx and add an AAD user?
In the logs, AzureCP records in VerboseEx the metadata properties it sets on users that it returns to the people picker.

**Comment by Yvand** [comment]
@totayo1000 any update on this?

**Comment by totayo1000** [comment]
Hi Yvand, i wasn't able to get any clue from the returned logs , I am creating a cloned environment and wanna try this as i am suspecting the way the mapping were done on azure .. as now i am facing a new issue with users logged on with their azure account to SharePoint and want to sync their document library to their PC OneDrive application they are getting access denied . in other words the onedrive PC application is treating  the azure AD account as a different entity then the actual active directory account for the same user

**Comment by Yvand** [comment]
@totayo1000 the SharePoint logs should show something like this:

```
11/08/2019 14:46:36.03	w3wp.exe (0x31C0)	0x0388	AzureCP	Claims Picking	1337	VerboseEx	[AzureCP] Set metadata 'Email' of new entity to 'yvand@TENANT.onmicrosoft.com'	11d7159f-c947-4003-d058-58405e97be7c
11/08/2019 14:46:36.03	w3wp.exe (0x31C0)	0x0388	AzureCP	Claims Picking	1337	VerboseEx	[AzureCP] Created entity: display text: 'yvand@TENANT.onmicrosoft.com', value: 'yvand@TENANT.onmicrosoft.com', claim type: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn', and filled with 4 metadata.	11d7159f-c947-4003-d058-58405e97be7c
```

As you can see, metadata Email was set in the entity, which is what you need

**Comment by totayo1000** [comment]
Hello Yvand
i have rebuilt a staging farm on sp2019  with the below configs
Azure claim attributes:
<img width="826" alt="657A8CFD" src="https://user-images.githubusercontent.com/55228538/69265352-fcbb9680-0bc0-11ea-813c-3071485c9a44.PNG">
and i run the below script to create the :

$realm = "urn:sharepoint:2016"
$wsfedurl="https://login.microsoftonline.com/586337a3-91dd-4b49-ac08-d11b29d94448/wsfed"
$filepath="C:/Certs/AADTokenSigningCert.cer"
$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($filepath)
New-SPTrustedRootAuthority -Name "AzureAD" -Certificate $cert
$map = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" -IncomingClaimTypeDisplayName "name" -LocalClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
$map2 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" -IncomingClaimTypeDisplayName "GivenName" -SameAsIncoming
$map3 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" -IncomingClaimTypeDisplayName "SurName" -SameAsIncoming
$map4 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn" -IncomingClaimTypeDisplayName "upn" -SameAsIncoming
$map5 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" -IncomingClaimTypeDisplayName "Groups" -SameAsIncoming
$ap = New-SPTrustedIdentityTokenIssuer -Name "AzureAD" -Description "SharePoint secured by Azure AD" -ImportTrustCertificate $cert  -realm $realm -ClaimsMappings $map,$map2,$map3,$map4,$map5 -SignInUrl $wsfedurl -IdentifierClaim "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"

Add-SPSolution -LiteralPath "C:\AzureCP.wsp"
Install-SPSolution -Identity "AzureCP.wsp" -GACDeployment
#Wait for Solution to Install before associating it with a SPTrustedIdentityTokenIssuer 
#Associate AzureCP with a SPTrustedIdentityTokenIssuer:
$trust = Get-SPTrustedIdentityTokenIssuer "AzureAD"
$trust.ClaimProviderName = "AzureCP"
$trust.Update() 

but this is what i got 

![Captureaz](https://user-images.githubusercontent.com/55228538/69265743-b4e93f00-0bc1-11ea-88fc-4dd9ecc634d6.PNG)

still not possible to add mail to picker ..

any advice's please ?

**Comment by Yvand** [comment]
@totayo1000 In your screenshot, PickerEntity Email is already set in the last line, it's why you cannot set it in emailaddress claim type.
You must delete the last line first, then you can set it in emailaddress claim type.

**Comment by totayo1000** [comment]
Hi Yvand 
I did that but it did not work , 
are my azure claim settings correct 
Thanks

**Comment by Yvand** [comment]
@totayo1000 sorry for the late reply, what happens when you try to add it, does any error is displayed in the page?

**Comment by totayo1000** [comment]
@Yvand no error is shown on the page , is there a way i can trace what is happening

**Comment by Yvand** [comment]
Does it work with any other PickerEntity? Are you able to assign the PickerEntity to a new dummy claim type?

**Comment by totayo1000** [comment]
No it does not work for any picker entity .. but it do work for a dummy claim type as below highlighted
![dummyclaim](https://user-images.githubusercontent.com/55228538/70305067-534ce580-17fb-11ea-987e-51740ad44512.PNG)

**Comment by Yvand** [comment]
I have no idea why this is not working, but in last resort, you can try to reset the configuration:
First you can try to click Reset from the AzureCP "Claim types configuration" page, it will only reset the list.
If it still does not work, you can do the reset from AzureCP "Global configuration" page, but this will revert all AzureCP configuration it is default state, you will lose all customization including the AAD tenant registered

**Comment by totayo1000** [comment]
@Yvand I tried both methods without success , would it be possible to have a Azure "Claim types configuration" page edited with breakpoints variable values to catch where this issue is occurring

**Comment by Yvand** [comment]
@totayo1000 sorry for this very late reply.
If are you still willing to investigate this issue, you can download the source code and private symbols corresponding to you released and do live debug with Visual Studio.
