### ISSUE TITLE
Guest Users in AzureAD are denied access in SharePoint despite being in SP group with permissions

### ISSUE THREAD

**Issue by vargasfe** [Yvand/AzureCP#66]
normal Users in AzureAD DomainA can login to SP without a problem
Guest users in AzureAD DomainA who are AzureAD DomainB users can login without problems
Guest users in AzureAD DomainA who have gmail.com account show up twice in people picker:
once with UserPrincipalName=user@gmail.com and once with Mail=user@gmail.com

If I try to add the Mail=user@gmail.com instance to the SP group I get the message "The user does not exist or is not unique."

If I add the UserPrincipalName=user@gmail.com instance to the SP group, the user is authenticated but gets Access Denied.
This was happening with AzureCP version 13 so I upgraded to AzureCP 15.1.20190715.926 but the problem persists.

I guess it must be a configuration mistake on my part but I don't know where.  Can you please help?

I have configured the TrustedIdentityTokenIssuer as follows:

$map  = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" -IncomingClaimTypeDisplayName "name" -LocalClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"
$map2 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" -IncomingClaimTypeDisplayName "givenname" -SameAsIncoming
$map3 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" -IncomingClaimTypeDisplayName "surname" -SameAsIncoming
$map4 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" -IncomingClaimTypeDisplayName "emailaddress" -SameAsIncoming
$map5 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/displayname" -IncomingClaimTypeDisplayName "displayname" -SameAsIncoming
$ap = New-SPTrustedIdentityTokenIssuer -Name $Name -Description "SharePoint secured by Azure AD" -realm $realm -ImportTrustCertificate $cert -ClaimsMappings $map,$map2,$map3,$map4,$map5 -SignInUrl $wsfedurl -IdentifierClaim "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"

**Comment by vargasfe** [comment]
further testing has revealed the following:

When "User identifier for 'Member' users:" is set to Mail, 
1. guest users with accounts in their own AzureAD are able to login successfully by virtue of SP group membership.
2. Guest users with user@gmail.com accounts are NOT able to login successfully despite SP group membership -(Why do you need access). 

When "User identifier for 'Member' users:" is set to UserPrincipalName:
1. guest users with accounts in their own AzureAD are NOT able to login successfully despite SP group membership.
2. Guest users with user@gmail.com accounts are able to login successfully by virtue of SP group membership

Is this a configuration issue with the TrustedIdentityTokenIssuer, or AzureCP, or AzureAD; or a bug somewhere else?

Thanks,

**Comment by Yvand** [comment]
Hi guys, the issues that you describe are related to [this uservoice](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/36274663-sign-in-to-sharepoint-2016-with-guest-accounts-is)

I verified that the solution implemented by the Azure AD team and described in the uservoice above works: when you set the source attribute of nameidentifier to "user.localuserprincipalname", both B2B and MSA guest accounts get a consistent value in the SAML token (in format user_mail.com#EXT#@Tenant.onmicrosoft.com).

For this to work well with AzureCP, you need to change AzureCP configuration to set "User identifier for 'Guest' users" to UserPrincipalName. Of course if you have existing Guest users added with previous configuration, they may not be able to sign-in after this change, and may need to be migrated to match the new value.

I plan to write a full article on this topic but I'm short in time for the moment. Please test this config and let me know if you have questions or comments

**Comment by Yvand** [comment]
@vargasfe did you make tests on this? 
FYI AzureCP 15.2, released last week, fixes an issue with the resolution of guest users

**Comment by vishnookumar** [comment]
> Hi @vargasfe, the issues that you describe are related to [this uservoice](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/36274663-sign-in-to-sharepoint-2016-with-guest-accounts-is)
> 
> I verified that the solution implemented by the Azure AD team and described in the uservoice above works: when you set the source attribute of nameidentifier to "user.localuserprincipalname", both B2B and MSA guest accounts get a consistent value in the SAML token (in format user_mail.com#EXT#@Tenant.onmicrosoft.com).
> 
> For this to work well with AzureCP, you need to change AzureCP configuration to set "User identifier for 'Guest' users" to UserPrincipalName. Of course if you have existing Guest users added with previous configuration, they may not be able to sign-in after this change, and may need to be migrated to match the new value.
> 
> I plan to write a full article on this topic but I'm short in time for the moment. Please test this config and let me know if you have questions or comments

Hi Yvand,
I have implemented the AzureCP. Changed the AzureCP configuration to set "User identifier for 'Guest' users" to UserPrincipalName. After that, searching for Guest Email address: vishnookumar@gmail.com is not resolving the user in people picker (Eg: when we copy paste the guest user email address). However, pasting the UPN (Eg: vishnookumar_gmail.com#EXT#@vishnoodev.onmicrosoft.com) is resolving the user. Can this be fixed?

**Comment by Yvand** [comment]
@vishnookumar to allow guest accounts to connect, there is a configuration on both sides: AzureCP and Azure AD.
Also, to avoid caching issues, you should always make your tests in a new site collection, each time you change the config in AzureCP

**Comment by vishnookumar** [comment]
@Yvand , I checked it on a new site collection as well, but the email ID of the guest is not resolving. Screenshot below.

When typing the guest user name:
![image](https://user-images.githubusercontent.com/70580406/92107767-f02cc580-ee03-11ea-80ed-6a2c6c24c08d.png)

When entering the guest user email ID:
![image](https://user-images.githubusercontent.com/70580406/92107925-308c4380-ee04-11ea-8bdb-90458fcce187.png)
