### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jeefberkey** [Yvand/AzureCP#67]
Sharepoint: Sharepoint Server 2019, all-in-one (version 16.0.10337.12109)
OS: Windows Server 2019 Datacenter (Version 1809, build 17763.805)

I'm having trouble following the installation guide for AzureCP. I have the following script in an admin session of Powershell ISE:

```powershell
Add-PSSnapin "Microsoft.SharePoint.PowerShell"

Add-SPSolution -LiteralPath "C:\Users\user\Downloads\AzureCP.wsp"
Install-SPSolution -Identity "AzureCP.wsp" -GACDeployment
<wait>

$trust = Get-SPTrustedIdentityTokenIssuer "AzureAD"
$trust.ClaimProviderName = "AzureCP"
$trust.Update()
```
It errors when I run the `$trust.ClaimProviderName = "AzureCP"` line:

```
PS C:\windows\system32> $trust.ClaimProviderName = "AzureCP"
Exception setting "ClaimProviderName": "Claim provider with name AzureCP does not exist."
At line:1 char:1
+ $trust.ClaimProviderName = "AzureCP"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
```
and if I run that command by itself to list all of the Claim Providers, it returns nothing.

I have also tried the debugging steps on [this page](https://yvand.github.io/AzureCP/Fix-setup-issues.html), but still no luck.

The outputs of these commands are as follows:

```
Get-SPClaimProvider | ft DisplayName
Get-SPSolution "AzureCP.wsp"| fl Name, Deployed
Get-SPFeature "AzureCP"| fl Name, Status
```
<details><summary>Output</summary>
<p>

```
PS C:\windows\system32> Get-SPClaimProvider | ft DisplayName
Get-SPSolution "AzureCP.wsp"| fl Name, Deployed
Get-SPFeature "AzureCP"| fl Name, Status

DisplayName                
-----------                
System                     
Active Directory           
All Users                  
Forms Auth                 
User Profile Claim Provider




Name     : azurecp.wsp
Deployed : True





Name   : FeatureDefinition/15/d1817470-ca9f-4b0c-83c5-ea61f9b0660d
Status : Online


```
</p>
</details>

**Comment by Yvand** [comment]
@jeefberkey this is strange, can you try to deactivate and reactivate farm feature AzureCP?
You can do that from central administration or with PowerShell

**Comment by jeefberkey** [comment]
I used central administration to deactivate and reactivate the feature. I didn't know you could do that, so that's cool. 

And it looks like that worked! I was able to update the `$trust` var and finish installation.

**Comment by vasiliiburca** [comment]
Thank you

**Comment by bed428** [comment]
> I used central administration to deactivate and reactivate the feature. I didn't know you could do that, so that's cool.
> 
> And it looks like that worked! I was able to update the `$trust` var and finish installation.

Worked for me as well!

I think my mistake was retracting the Farm Solution EntraCP, before deactivating the feature. (To test the UPA Claims provider and see if it was sufficient.... clearly it was not 😉.) Simple fix though!
