### ISSUE TITLE
Unable to assign permissions on SharePoint onPremise with AzureCP to Security groups having '{' in the name

### ISSUE THREAD

**Issue by sumanthraichuracn** [Yvand/AzureCP#69]
Hello Yvand,

We have a SharePoint OnPremise site which is integrated with Azure AD authentication along with ADFS 4.0, We have installed AzureCP to manage the claims.

We are successfully able to search for the users and assign permissions to them, but we are facing an issue with the security groups. 

Our Active Directory has certain security groups which have a { in the group name, these groups are synced to Azure Active Directory through the Azure AD Connect Sync.

We are unable to add these groups on the SharePoint site as they don't show up when searched in the people picker. 

Below are the logs which were found in ulsviewer:
**[AzureCP] Unexpected error occurred in SearchOrValidate: System.FormatException: Input string was not in a correct format.,** Callstack:  
 at System.Text.StringBuilder.FormatError()  
 at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)  
 at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)  
 at azurecp.AzureCP.BuildFilter(OperationContext currentContext, List`1 azureTenants)  
 at azurecp.AzureCP.SearchOrValidateInAzureAD(OperationContext currentContext)  
 at azurecp.AzureCP.SearchOrValidate(OperationContext currentContext)

**Comment by sumanthraichuracn** [comment]
Also I would like to confirm a few things:
1. The same  works on SharePoint Online
2. The same works with LDAPCP with SharePoint OnPremise and we are able to add site permissions to groups which have { in their names with LDAPCP.

**Comment by Yvand** [comment]
@sumanthraichuracn thank you for reporting this, this is caused by String.Format that throws an exception if input contains a '{', as [explained here](https://stackoverflow.com/questions/1118529/string-format-exception-when-format-string-contains)

I just replaced it with String.Replace in https://github.com/Yvand/AzureCP/commit/1ffe4874eae483d95e2e53d0139cddad94234e8d

**Comment by sumanthraichuracn** [comment]
> @sumanthraichuracn thank you for reporting this, this is caused by String.Format that throws an exception if input contains a '{', as [explained here](https://stackoverflow.com/questions/1118529/string-format-exception-when-format-string-contains)
> 
> I just replaced it with String.Replace in [1ffe487](https://github.com/Yvand/AzureCP/commit/1ffe4874eae483d95e2e53d0139cddad94234e8d)

Hello Yvand,

Thanks for responding to us. Do you mean to say you already fixed it in this commit (1ffe487).

Should we download a latest version of AzureCP now and give it a try or you want us to modify the files manually?

Thanks,
Sumanth

**Comment by Yvand** [comment]
The fix is committed but there is no new version of AzureCP published yet.
I don't know when I'll release it, I'll update this thread when it is available.

**Comment by sumanthraichuracn** [comment]
Could you please guide me how I can add this changed code in my AzureCP.wsp file?

**Comment by Yvand** [comment]
@sumanthraichuracn I just published a pre-release of AzureCP 15.3, which includes the fix for this issue, it is available [here](https://github.com/Yvand/AzureCP/releases/tag/15.3.20191120.1028).
Can you please test it and let me know if it works fine?
To update AzureCP, follow **all the steps** described at https://yvand.github.io/AzureCP/Update-AzureCP.html

**Comment by Yvand** [comment]
@sumanthraichuracn were you able to test the pre-release?

**Comment by Yvand** [comment]
@sumanthraichuracn last chance to give feedback before I publish the release

**Comment by Yvand** [comment]
Bug resolved in 15.3 https://github.com/Yvand/AzureCP/commit/0132206b215efc28bfdd2ed649c6629e6a9064cf

**Comment by sumanthraichuracn** [comment]
Thanks Yvan for the support. Much Appreciated.

Thanks & Regards,
Sumanth A Raichur
Accenture Security
Accenture Solutions India [p] Ltd.
+ Bangalore, Karnataka 560059 India
Mobile: (91) 9740284382

Upcoming Planned Leaves : Jan 31st  , Feb 3rd
