### ISSUE TITLE
ACS Retirement

### ISSUE THREAD

**Issue by flyingMagnus** [Yvand/AzureCP#7]
With Microsoft announcing the retirement of ACS for November 2018, have you looked at migration options to authenticate directly with Azure AD, bypassing ACS?

**Comment by Yvand** [comment]
AzureCP cannot substitute ACS, both have a completely different role.
But ACS can be replaced by ADFS (which would trust Azure AD directly without using ACS). This would change nothing for AzureCP as it would continue to query Azure AD.

**Comment by guptas-abhishek** [comment]
Hi Yvand,

Thanks for your comment to flyingMagnus,  I also have the same query which you answered partially but the other half which i am not able to understand is that -- as of now if we need to configure and connect Azure CP with out Sharepoint 2013 as Custonm Claims Provider, we give info (screenshot attached) like Provider URI, ProviderRealms, UPN etc  but when you create  Azure AD application, we dont create all these.
Apart from this, the certificate which we extract was from ws federation metadata xml file and extracting the certificate inside the tag  signing and x509 . In Azure AD, if  I see the WS federation metadata xml file  I see 3 seperate entries each inside a signing and x509.

Bit Lost ... Can you please throw some light on this or any document for me to refer ?

**Comment by Yvand** [comment]
Hello,
You can use ADFS as an intermediate between SharePoint and Azure AD. 
ADFS will get the SAML 2.0 token from Azure AD and generate a proper SAML 1.1 token that SharePoint can understand.
In this scenario SharePoint trusts ADFS (and its signing certificate).
The configuration to make is described in [this blog post](https://blogs.msdn.microsoft.com/mrochon/2017/04/07/using-azure-ad-to-enable-partner-access-sharepoint).
Does it make sense?

**Comment by stevep4** [comment]
Just to update things here:

https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication

AAD can now issue SAML 1.1 directly... which I've got working.

Then I came across AzureCP, and I'm really muddled should I use this instead of the MS method, or do they work hand in hand?!

**Comment by Yvand** [comment]
Hello, yes you can now federate Azure AD directly with SharePoint, which is very good news since you don't need ADFS anymore.
But this doesn't really change anything for AzureCP, it talks with Azure AD the same way, whether you ADFS or not.

**Comment by Yvand** [comment]
Hi @stevep4 
AzureCP can fix the display name of users if:
- User is added for the very first time in the site collection (if user was deleted and is re-added this won't work)
- In central admin > Security > AzureCP claims mapping page: a Graph property has the Metadata "DisplayName" set

But, whatever you configure this or not, the User Profile Application service is the component that synchronizes the display name from the User Profiles to the site collections.
So if your trusted users have a valid user profile in the UPA, their display name will be synced from this profile.
