### ISSUE TITLE
Installation ISSUE

### ISSUE THREAD

**Issue by vasiliiburca** [Yvand/AzureCP#73]
Hello,
I have an issue installing the solution please see the picture:

![image](https://user-images.githubusercontent.com/32271922/71261495-2c87c680-2346-11ea-8b6c-a62ee64b2d15.png)

I am able to install it by passing -Force argument at the end of the command but I get another error by forcing it: (IT seem like it does not register a Claim Provider)

Exception setting "ClaimProviderName": "Claim provider with name AzureCP does not exist."
At line:1 char:1
+ $trust.ClaimProviderName = "AzureCP"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting

**Comment by Yvand** [comment]
This happens sometimes with SharePoint, carefully follow article https://yvand.github.io/AzureCP/Fix-setup-issues.html to fix it

**Comment by Yvand** [comment]
@vasiliiburca did you resolve the issue?
