### ISSUE TITLE
Debug AzureCP group claims 

### ISSUE THREAD

**Issue by martinaffectoericsson** [Yvand/AzureCP#74]
Hi,
I would like to debug AzureCP and would like to view all group/role claims for a logged on user. I have done this for adfs before with Fiddler. If I use that method I can see all group claims derived from Azure security groups. That’s great but I was looking for my claims from 0365 groups that I use inside SP on-Prem as access groups. The AzureCP works great but I need to find a solid method for this when access issues occur. Thanks in advanced! Rgds Martin

**Comment by Yvand** [comment]
@martinaffectoericsson the easiest way to see all the groups returned by AzureCP is to check SharePoint logs and filter on product/area "AzureCP". If you set it to verbose, you will see all groups returned for users.
You can also download the source code / private symbols published with each release, and live debug with Visual Studio.

**Comment by martinaffectoericsson** [comment]
Thanks a lot!!
