### ISSUE TITLE
"Modified By" metadata

### ISSUE THREAD

**Issue by hat-cat** [Yvand/AzureCP#75]
The "Modified By" metadata (for documents, site pages, etc.) currently shows our users' UPN, but we would like it to show the Display Name instead:
![image](https://user-images.githubusercontent.com/60277556/73111884-ec75af80-3ec0-11ea-8493-51b7c60083bf.png)

I looked into our user profiles and UPN is being mapped to the Preferred Name filed as well. Is there any way to change these mappings? 

Thank you!

EDIT: I've provided SAML configurations / mappings in issue https://github.com/Yvand/AzureCP/issues/76

**Comment by hat-cat** [comment]
I found the answer in this issue - https://github.com/Yvand/AzureCP/issues/7

In AzureCP claim types config, I needed to add a mapping for DisplayName on object User to picker entity DisplayName. 

I tried this before, but now I realize that my tests of deleting the user then re-adding were not working. 

This is resolved, but I would like to know - is there an easy way for me to fix the user profiles with the incorrect name? Or do I have to change the settings myself for each user profile. 

Thanks!

**Comment by Yvand** [comment]
The format shown in people columns is determined by the display name of the user profile, set in the User Profile Application.
AzureCP itself has a very limited (almost none) ability to set the format displayed in this column, you can consider that it is not playing a role.

**Comment by hat-cat** [comment]
Ah, I understand now that this is a UPS configuration problem.

Does AzureCP work with profiles imported from on-prem AD when using Azure Active Directory Sync? When I set up the User Profile Service application to import from our on-prem AD, I ran into a problem where users authenticated via Azure AD do not start using the imported profile. 

Essentially it led to a case where there were two user profiles for the same user: "domain\testuser" and "i:0e.t|azuread|testuser@domain", and these profiles were accessed separately depending on authentication method. 

Or should I be importing from AzureAD directly / what are the requirements to ensure the Azure-authenticated user grabs the imported profile?  

I really appreciate the help & I apologize for my inexperience on the subject.

**Comment by Yvand** [comment]
This area is poorly documented, so it's perfectly understandable that you are confused.
The important thing to understand are:
- "i:0#.w|domain\testuser" and "i:0e.t|azuread|testuser@domain" are NOT the same user, as far as SharePoint is concerned they are 2 completely different users
- User Profile Service application has nothing to do with permissions, its only purpose is to populate metadata about the users

**Comment by Yvand** [comment]
Closing this issue, feel free to reopen it if needed
