### ISSUE TITLE
Cannot send "People with existing access" share link to external guest user

### ISSUE THREAD

**Issue by hat-cat** [Yvand/AzureCP#76]
When sharing a document by sending a link, if I set the type to "People with existing access" before picking an external guest user, the Send Link dialogue claims that the recipient does not have permissions to access the item: 
![image](https://user-images.githubusercontent.com/60277556/73112351-ee407280-3ec2-11ea-8469-b2aacec10753.png)

I have confirmed that the external guest user in question has appropriate permissions. This error does not apply to internal users. 

For reference, I'm attaching configs for my identity token issuer, SAML attributes and claims, and AzureCP claims mapping.

Identity token issuer: 
![image](https://user-images.githubusercontent.com/60277556/73112755-d79b1b00-3ec4-11ea-956a-8c2f9495757d.png)

SAML attributes and claims (Azure portal):
![image](https://user-images.githubusercontent.com/60277556/73112716-a3bff580-3ec4-11ea-82da-2effe15d9180.png)

AzureCP 
![image](https://user-images.githubusercontent.com/60277556/73112823-3f516600-3ec5-11ea-9e73-240f781195b8.png)

Any assistance with this would be greatly appreciated, as it is within the scope of my project to have Sharepoint Server function as close to Sharepoint Online as possible. 

Thank you!

**Comment by hat-cat** [comment]
I went to AzureCP global config and changed the user identifier for guest users to E-mail, which fixed the sending problem. However, this change blocked guest users from signing in (even though I re-added them to the site after the identifier change), so the problem remains.

**Comment by Yvand** [comment]
You should not change the default configuration of AzureCP, the mapping must be set with the UPN since its the configuration in Azure AD.

I tested this scenario to understand how it works.
To be able to use this dialog, the user you select must have his email synchronized from the User Profile to the current site collection.
As soon as the email was present, I was able to send him an email invitation, otherwise the "Send" button is disabled.

Can you try that?

**Comment by hat-cat** [comment]
I added the user's e-mail under "Work E-mail" in their user profile, and made sure that the site collection had the updated information before testing. It still will not send the link, claiming that they don't have access. This problem only applies to the "users with existing access" link option; the other options for sending a link work as expected. 

I'm willing to put this issue aside until I have User Profile Service synchronization connection set up, since I feel it would be appropriate to have the core components set up before troubleshooting a smaller issue like this. Which, at this point, I feel head-over-heels in this matter as Microsoft's [documentation for AzureAD](https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial) integration has not given me an adequate idea of what needs to happen for this to actually work.

**Comment by Yvand** [comment]
@hat-cat I did the exact same test as you described and it fixed the error message, but I didn't validate the user received the link (I tested with a fake email). Did you double check that the mail was synchronized the the local user profile in the current site collection?

Yes it's a good idea to properly sync profile properties but the test was anyway relevant.

**Comment by Yvand** [comment]
@hat-cat any news on this?

**Comment by Yvand** [comment]
Closing this issue due to lack of response, feel free to reopen it if needed
