### ISSUE TITLE
Additional Unique Identifiers?

### ISSUE THREAD

**Issue by Grime121** [Yvand/AzureCP#77]
Is there any way to add an additional unique identifier? We do not use our On-Prem UPNs as the unique identifiers in Azure. We use the mail attribute. For SharePoint we use DOMAIN\username format, but would also be OK with using the ON-PREM UPNs (username@on-premisedomain.local). We have to use one of those two because we have custom code that needs to find the user using their domain name and username (those two attributes are stored in our HR database, whereas email addresses are not).

So, I'm wondering if there is a way to get AzureCP to use either DOMAIN\username or username@on-premdomain.local format for the unique identifier. Obviously the Azure Application would also need to be changed to return this information as well. I know Enterprise Applications are capable of this, but I'm not sure if the type of Azure Application AzureCP uses is capable of it. I do know both of these are stored on the AD accounts in Azure. It's just a matter at figuring out how to get to the data....

**Comment by Yvand** [comment]
AzureCP allows you to choose what Azure AD attribute should be used as the unique identifier. You can do that in Central Administration > Security > AzureCP global configuration, and set the "user identifier property".
Of course, this attribute must match the one you set in the Azure AD Enterprise Application for SharePoint.
Note that the Azure AD application created for AzureCP is not playing any role here.

**Comment by Grime121** [comment]
Is there a way to add additional options to that list though? For instance, the On-Prem UPN attribute, or the DOMAIN\username formatted-attribute (not sure what it’s called)? I know these are available attributes in Azure... We use them for the Trusted Identity Provider....

---
Evan Talley
etalley@gmail.com

> On Feb 4, 2020, at 3:13 AM, Yvan Duhamel <notifications@github.com> wrote:
> 

﻿
AzureCP allows you to choose what Azure AD attribute should be used as the unique identifier. You can do that in Central Administration > Security > AzureCP global configuration, and set the "user identifier property".
Of course, this attribute must match the one you set in the Azure AD Enterprise Application for SharePoint.
Note that the Azure AD application created for AzureCP is not playing any role here.

**Comment by Yvand** [comment]
Unfortunately this list is not dynamic, it is a simple enumeration type.
I will update it to include all the [possible properties for User class](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties), but you will need to update AzureCP to use it.

**Comment by Grime121** [comment]
That would be great. Thanks!

> On Feb 5, 2020, at 4:24 AM, Yvan Duhamel <notifications@github.com> wrote:
> 

﻿
Unfortunately this list is not dynamic, it is a simple enumeration type.
I will update it to include all the possible properties for User class, but you will need to update AzureCP to use it.

**Comment by Yvand** [comment]
@Grime121 I added the missing properties in https://github.com/Yvand/AzureCP/commit/9439b99a24f1bc163642767959177c453b67f137 and it will be available in the next version.
Please let me know if you have any comment

**Comment by Grime121** [comment]
Excellent! This is a huge help. Thanks!
