### ISSUE TITLE
AzureCP not associate with any TrustedLoginProvider

### ISSUE THREAD

**Issue by antuantc** [Yvand/AzureCP#81]
Can you help me to get through this error so I can add a tenant to AzureCP?

![image](https://user-images.githubusercontent.com/9366859/74884398-b64d1380-5338-11ea-83d0-096c573badea.png)

**Comment by jeefberkey** [comment]
Re-run this section from the [installation](https://yvand.github.io/AzureCP/Install-AzureCP.html):

```
$trust = Get-SPTrustedIdentityTokenIssuer "SPTRUST NAME"
$trust.ClaimProviderName = "AzureCP"
$trust.Update()
```

**Comment by Yvand** [comment]
Thanks @jeefberkey for helping out
@antuantc can this issue be closed?

**Comment by antuantc** [comment]
Hi,

That suggestion did not work but you can go ahead and close it.  Once I get
some time, I will try it from the beginning.

thanks,
Tuan
