### ISSUE TITLE
Unexpected [AzureCP] Cannot continue because identity claim type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn' set in the SPTrustedIdentityTokenIssuer 'AzureAD' is missing in the ClaimTypeConfig list. 69a34f9f-dafc-c0d8-649e-a10bf4e3a569

### ISSUE THREAD

**Issue by upatel911** [Yvand/AzureCP#85]
However got the following issues. Need your expert advise to fix this issue.
We have 3 tier farm.

Application Server (Running Central Admin Site and Search)
WFE1 (load balancing)
WFE2 (load balancing)
The People Picker Control not working and not giving any results when request go to WFE1.
The People Picker Control working fine on WFE2 when search for the users.
We have checked the ULS Logs on WFE1 and found the following errors multiple times...
Unexpected [AzureCP] Cannot continue because identity claim type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn' set in the SPTrustedIdentityTokenIssuer 'AzureAD' is missing in the ClaimTypeConfig list. 69a34f9f-dafc-c0d8-649e-a10bf4e3a569
05/05/2020 23:31:27.32 w3wp.exe (0x20F0) 0x25F4 AzureCP Core 1337

**Comment by Yvand** [comment]
@upatel911 Can you reset the AzureCP claim types mapping? You can do that in the central administration > security > AzrueCP claim types mapping page, and click on button Reset configuration.

**Comment by Yvand** [comment]
Closing issue due to no response, feel free to reopen it if needed
