### ISSUE TITLE
AzureCP is not able to find UPN in AzureAD

### ISSUE THREAD

**Issue by abhishek0818** [Yvand/AzureCP#87]
hi Team,

I have performed integration of sharepoint wth AAD from https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial#additional-resources link. But my testing is not successful.

Following is the details regarding my testing scenario.
Given - 
1. I have one sharepoint server and userId (firstname.lastname@domain.local), using this userId I can access sharepoint site internally without integrating with AAD.
2. I have created one application in AAD and have a userId(firstname.lastname@comapanyemail.com) and this userId has an UPN configured in "user.extensionattribute1" custom attribute.

Testing -

1. as per documentation when I set claims "name" and "unique identifier" with value "user.localuserprinciplename" then user is getting authenticated successfully but the home page of sharepoint is not as same as #1 in given part.
2. when I set claim "name" with value "user.extensionattribute1" then after login through AAD, SAML claims are getting sent to AzureCP, and AzureCP tries to find "firstname.lastname@domain.local" userId which it receives from claim "name" and tries searching it in AAD with value as "firstname.lastname@domain.local" and type as UPN, but as this value is not present in AAD as UPN then  AzureCP throws an error  saying found 0 record for this match.

Notes -
AzureCP is configured with default configuration as below : 
$realm = "urn:sharepoint:federation"
$wsfedurl="URL"
$filepath="certificate apth"
$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($filepath)
New-SPTrustedRootAuthority -Name "AzureAD" -Certificate $cert
$map1 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" -IncomingClaimTypeDisplayName "name" -LocalClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"
$map2 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" -IncomingClaimTypeDisplayName "Role" -SameAsIncoming
$ap = New-SPTrustedIdentityTokenIssuer -Name "AzureAD" -Description "Azure AD SharePoint server 201x" -realm $realm -ImportTrustCertificate $cert -ClaimsMappings $map1,$map2 -SignInUrl $wsfedurl -IdentifierClaim $map1.InputClaimType

Problem Identifier Path - 
I have identified from testing that if AzureCP searches for "mail" instead of "UPN" for value it received from claim "name" in SAML response from AAD then we'll be good for our testing to get passed.

For this I already tried editing AzureCP claims configuration but it is not getting edited successfully.

Could you please help checking on this part and let me know if you need any help on this.

Thanks
Abhishek

**Comment by Yvand** [comment]
Closing issue due to no response, feel free to reopen it if needed
