### ISSUE TITLE
Having issue with using AzureCP on SharePoint 2019 with June CU 16.0.10359.20000

### ISSUE THREAD

**Issue by kghoang77** [Yvand/AzureCP#89]
Having issue with using AzureCP on SharePoint 2019 with June CU 16.0.10359.20000

The install went through fine.  But the name resolution doesn't work with AzureAD.

Thanks
Khanh

**Comment by Yvand** [comment]
Did you configure the tenant?
Can you look at the SharePoint logs and filter on product/area "AzureCP" to see what is happening?
