### ISSUE TITLE
Azure AD Users not appearing post Azure CP Configure

### ISSUE THREAD

**Issue by sikandersa** [Yvand/AzureCP#91]
Have installed AzureCP v16 on our on-prem SharePoint 2013 Farm. However when trying to add users to a site, the on-prem AD account is showing, and the Azure AD account is not showing in the people picker with AzureCP. 
In other words, I cannot select the correct Azure AD account which works without Azure CP with Name/Role Claims mapping which we have defined with this article : https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial#additional-resources

**Comment by Yvand** [comment]
@sikandersa can you check the SharePoint logs and filter on Product/Area "AzureCP" to see what happens?

**Comment by sikandersa** [comment]
Unexpected    [AzureCP] Unexpected error(s) occurred while querying Azure AD tenant 'Tenant Name':  [EXCEPTION 1]: Microsoft.Graph.ServiceException: Code: Authorization_RequestDenied  Message: Insufficient privileges to complete the operation.
Directory Read all permission was already given

**Comment by Yvand** [comment]
Can you send a screenshot of the permissions page in the Azure AD tenant?
