### ISSUE TITLE
Migration of Windows AD Account to Azure AD for SharePoint

### ISSUE THREAD

**Issue by sikandersa** [Yvand/AzureCP#92]
We have configured from Windows AD to Azure AD authentication for Sharepoint following the below article and need to know how we can mapp the access for Azure AD account permissions (from Windows credentials to Azure AD)

https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial

**Comment by Yvand** [comment]
Sorry but your question is way too vague. What did you try and what does not work?

**Comment by sikandersa** [comment]
How we need to migrate the permissions from Windows Claims to Azure ID post switching the authentication from Windows to Azure trusted identity token issuer

**Comment by Yvand** [comment]
You can use [SPFarm.MigrateUserAccount](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.administration.spfarm.migrateuseraccount?view=sharepoint-server#Microsoft_SharePoint_Administration_SPFarm_MigrateUserAccount_System_String_System_String_System_Boolean_):

```powershell
$oldlogin="i:0#.w|AD\user1";
$newlogin="i:05.t|azuread|user1@tenant.com";
[Microsoft.SharePoint.Administration.SPFarm]::Local.MigrateUserAccount($oldlogin, $newlogin, $false);
```

**Comment by sikandersa** [comment]
Can we restrict to Site Collection level for migrating the user permission from source to destination ?

**Comment by Yvand** [comment]
No, migration is farm wide
