### ISSUE TITLE
Issue when logging on as a user withing a group added by azurecp

### ISSUE THREAD

**Issue by jconduit** [Yvand/AzureCP#93]
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:   
 at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)    
 at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)

**Comment by Yvand** [comment]
Somehow, some assemblies that AzureCP depends on are missing in the SharePoint server.
You can unzip AzureCP.wsp using [7-zip](https://www.7-zip.org/), and compare the assemblies in the archive with the ones present in the GAC of the machine (C:\Windows\Microsoft.NET\assembly\GAC_MSIL) to find which ones are missing.
You can also apply the PowerShell script in https://yvand.github.io/AzureCP/Install-AzureCP.html to automatically install all of them
