### ISSUE TITLE
Group User is not able to login Error [AzureCP] Unexpected error(s) occurred in AugmentEntity

### ISSUE THREAD

**Issue by gauravPOC** [Yvand/AzureCP#94]
I have Already setup AzureCP for 2 farm and working fine. But for other farm same configuration giving below error :[AzureCP] Unexpected error(s) occurred in AugmentEntity. 

When i have done some deep study then i found when i unchecked "Augmentation" option then it  works file but then Azure AD group user doen not work.

I have uplaoded the error log. Please help
[errror.txt](https://github.com/Yvand/AzureCP/files/4902156/errror.txt)

**Comment by gauravPOC** [comment]
Adding some more logs from AzureCP product Area
[azurecp.txt](https://github.com/Yvand/AzureCP/files/4903662/azurecp.txt)

**Comment by Yvand** [comment]
AzureCP cannot get an access token for your tenant:
`07/10/2020 11:38:32.82	w3wp.exe (HCLT-PC4814-1:0x3C10)	0x4550	AzureCP	Core	1337	Unexpected	[AzureCP] Could not get access token before timeout of 4000 ms for tenant 'XXX'	
Do you need to configure a proxy? Did you configure the proxy in the w3wp of SharePoint STS?

**Comment by gauravPOC** [comment]
Thanks Yvan. I am not using any proxy. But when  I unchecked "Augmentation" option then it works file. still it seems to be proxy issue.

**Comment by gauravPOC** [comment]
I have downloaded fiddler and test the application then it is working fine but after closing fiddler it again stopped. it seems something block from network side. i have gone through the log and it stuck when it move to /_trust/default.aspx to 
graph.microsoft.com:443
/v1.0/users?$filter=UserPrincipalName+eq+%27gaurav-a%40hcl.com%27
/v1.0/users/24bdad81-3f6f-4816-9382-4907830622a1/microsoft.graph.getMemberGroups

Please let me know what change i need to on network side.

**Comment by Yvand** [comment]
@gauravPOC the symptoms you describe really look like a SSL trust issue. Can you enable CAPI2 logs in the event viewer and reproduce the error?

**Comment by gauravPOC** [comment]
I had apply proxy and it is stated working fine. But my question is there any way to work w/o proxy. Can i exclude Graph API call from firewall.

**Comment by Yvand** [comment]
It depends on your infrastructure, only your network/security teams can answer this question.

**Comment by gauravPOC** [comment]
Thankyou very much Yvan. Much appreciated.

Regards
Gaurav
________________________________
