### ISSUE TITLE
Unable to get access token for tenant '189de737-c93a-4f5a-8b68-6f4ca9941912': One or more errors occurred. 

### ISSUE THREAD

**Issue by gauravPOC** [Yvand/AzureCP#96]
Hi Yvan,

I am unable to connect AzureCP  from central admin after giving Tenant ID, Application ID and Client secret and click on Test Connection its giving below error
 Unable to get access token for tenant '189de737-c93a-4f5a-8b68-6f4ca9941912': One or more errors occurred. 

I have also implement proxy on server and checked but no luck.

After enable Verbose log i getting below Error :-
[] Unexpected error occurred while getting access token for tenant '189de737-c93a-4f5a-8b68-6f4ca9941912': System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive., Callstack:   
 at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)    
 at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

I have also take the log of fiddler for this specific error. Please find file as an attachment.
[AzureCP.zip](https://github.com/Yvand/AzureCP/files/4975429/AzureCP.zip)

My initial impression is it is related to TLS but i am unable to find out where is the issue. Please help to resolve this.

**Comment by Yvand** [comment]
can you sign-in to the SharePoint server as the application pool / farm account, open IE and try to browse the following sites:

* https://login.windows.net
* https://login.microsoftonline.com
* https://graph.microsoft.com

If one does is not accessible / shows errors, AzureCP cannot work, as they are all required for Graph API to work.

**Comment by gauravPOC** [comment]
Thanks Yvan. Your doubt is correct. This is because of TLS which restricted the communication between AzureCP to AzureAD. i have disable TLS 1.0 and 1.1 and enable TLS 1.2 only and it works fine. Thanks a lot for your help.
