### ISSUE TITLE
Remove AD claim Provider 

### ISSUE THREAD

**Issue by gauravPOC** [Yvand/AzureCP#97]
Hi Yvan,

After enableing the AzureCP Trusted Identity Provider on the web application for Azure AD, We need to enable Windows Authentication (which is required for Search Crawling account on the Default zone), and i have also hide the Window AD claim Provider using below script using given blog.
$cpm = Get-SPClaimProviderManager
$cp = Get-SPClaimProvider -Identity "AD"
$cp.IsVisible = $false
$cpm.Update()

https://blog.octavie.nl/index.php/2019/07/09/managing-the-peoplepicker-when-custom-claims-providers-exist

But the issue is - 80% User getting window ID in People picker suggestion from cache and it save in SharePoint list like 'i:0#.w|domainname\Username and it takes to wrong data save.

I am looking any way if we can disable window ID  therefore when it is come from cache then while saving its give error that User does not exists. or any other way to clear people picker cache from script.

Your early response is highly appreciate as we have already gone on production.

Regards
Gaurav

**Comment by gauravPOC** [comment]
HI Yvan,

Do we setup AzureAD authentication on any other zone . Will AzureCP support or it is supports only on Default zone. i am looking alternate to crawl search as Search can only crawl with default zone then OWA is working otherwise lots of issue coming.

Please help

Regards
Gaurav

**Comment by gauravPOC** [comment]
Please help to resolve this issue.

Regards
Gaurav

**Comment by Yvand** [comment]
AzureCP returns entities from any zone, as long as it is enabled in at least 1 zone.
